import {createGamepadControls} from './gamepad-controls.js';
import {createTiltControls} from './tilt-controls.js';
import {buildRoadGraph,spawnRoad,roadPosition,advanceRoad,reverseRoad,bearing,angleGap,toLngLat} from './auto-roads.js';
import {createCar,advanceCar} from './auto-physics.js';
import {createDrivingWorld} from './auto-world.js';
import {createSpring,advanceSpring} from './flight-physics.js';
let setupPromise;
export async function startAuto(map){if(!setupPromise)setupPromise=setup(map).catch(e=>{setupPromise=null;throw e;});const controller=await setupPromise;controller.start();}
async function setup(map){
 const [T,modelModule,response]=await Promise.all([import('https://unpkg.com/three@0.169.0/build/three.module.js'),import('./auto-model.js'),fetch('./district-data.json')]);if(!response.ok)throw new Error('Road data unavailable');const data=await response.json(),graph=buildRoadGraph(data),world=createDrivingWorld(data,graph);
 const model=modelModule.createAuto(T),scene=new T.Scene(),camera=new T.Camera();scene.add(model.group,new T.HemisphereLight(0xcde6ed,0x766653,2.1));const sun=new T.DirectionalLight(0xfff0d4,2.5);sun.position.set(-20,-30,60);scene.add(sun);
 // Metre-width surfaces remain readable when zoomed beyond the basemap style.
 const roads={type:'FeatureCollection',features:graph.edges.map(e=>{const a=graph.nodes[e.a].p,b=graph.nodes[e.b].p,w={service:2.5,minor:3.5,tertiary:5,secondary:6,primary:7,trunk:8}[e.kind]||3.5,dx=(b[0]-a[0])/e.length,dy=(b[1]-a[1])/e.length;const ring=[[a[0]-dy*w-dx*.3,a[1]+dx*w-dy*.3],[b[0]-dy*w+dx*.3,b[1]+dx*w+dy*.3],[b[0]+dy*w+dx*.3,b[1]-dx*w+dy*.3],[a[0]+dy*w-dx*.3,a[1]-dx*w-dy*.3]];ring.push(ring[0]);return{type:'Feature',properties:{},geometry:{type:'Polygon',coordinates:[ring.map(toLngLat)]}}})};
 map.addSource('auto-roads',{type:'geojson',data:roads});map.addLayer({id:'auto-road-surface',type:'fill',source:'auto-roads',layout:{visibility:'none'},paint:{'fill-color':'#555c59','fill-antialias':false}},'district-detail');
 let car,cameraRig,lookRig;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const keys=new Set();let active=false,paused=false,path,speed=0,distance=0,heading=0,choice='straight',last=0,raf=0,wheelAngle=0,oldCamera,oldMax,oldHandlers,oldSymbols=[],wide=false,renderer,noticeUntil=0;
 const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 const hud=document.createElement('section');hud.id='auto-hud';hud.hidden=true;hud.innerHTML=`<div class="flight-top"><div><span class="sub">BENGALURU / AUTO</span><strong>CBD drive</strong></div><button id="exit-auto">Exit drive</button></div><div class="instruments"><div><strong id="auto-speed">0</strong><span>km/h</span></div><div><strong id="auto-distance">0.00</strong><span>km driven</span></div><div><strong id="auto-turn">N</strong><span>gear</span></div></div><div class="flight-actions"><button id="pause-auto">Pause</button><button id="auto-camera">Wide view</button><button id="reset-auto">Reset auto</button></div><p id="auto-message" role="status" aria-live="polite">↑ Accelerate · ↓ Brake / reverse · ← → Steer · Space Stop</p><span class="sub">Free steering · CBD · Arcade vehicle physics</span>`;document.body.appendChild(hud);
 const controls=document.createElement('section');controls.id='auto-controls';controls.hidden=true;controls.innerHTML=`<div class="auto-turn-controls"><button data-auto-key="ArrowLeft" aria-label="Steer left">← Steer</button><button data-auto-key="Space">Stop</button><button data-auto-key="ArrowRight" aria-label="Steer right">Steer →</button></div><div class="auto-pedals"><button data-auto-key="ArrowDown">↓ Brake / reverse</button><button data-auto-key="ArrowUp" class="primary">↑ Accelerate</button></div>`;document.body.appendChild(controls);
 const gamepad=createGamepadControls(hud,'auto');
 const tilt=createTiltControls(hud,()=>active&&!paused);
 function message(text){$('auto-message').textContent=text;noticeUntil=performance.now()+4000;}
 function release(){keys.clear();document.querySelectorAll('[data-auto-key]').forEach(b=>b.classList.remove('held'));}
 function pause(value){paused=value;release();last=0;$('pause-auto').textContent=paused?'Resume':'Pause';message(paused?'Drive paused. Resume when ready.':'Controls active.');}
 function updateCamera(dt=0){const a=car.heading*Math.PI/180,scale=innerWidth<761?1.35:1,behind=(wide?20:8.5)+Math.abs(car.speed)*.13,up=wide?19:4.8;const target={x:car.x-Math.sin(a)*behind*scale+Math.cos(a)*1.2,y:car.y-Math.cos(a)*behind*scale-Math.sin(a)*1.2,z:up*scale},look={x:car.x+Math.sin(a)*2,y:car.y+Math.cos(a)*2,z:1};if(!cameraRig||!dt||reduced){cameraRig=createSpring(target.x,target.y,target.z);lookRig=createSpring(look.x,look.y,look.z);}else{advanceSpring(cameraRig,target,dt,5);advanceSpring(lookRig,look,dt,9);}map.jumpTo(map.calculateCameraOptionsFromTo(toLngLat([cameraRig.x,cameraRig.y]),cameraRig.z,toLngLat([lookRig.x,lookRig.y]),lookRig.z));}
 function reset(){path=spawnRoad(graph);const p=roadPosition(graph,path);car=createCar(p[0],p[1],bearing(graph.nodes[path.from].p,graph.nodes[path.to].p));speed=distance=wheelAngle=0;heading=car.heading;cameraRig=lookRig=null;pause(false);updateCamera();message('↑ Accelerate · ↓ Brake / reverse · ← → Steer · Space Stop');map.triggerRepaint();}
 function updateHUD(){ $('auto-speed').textContent=Math.round(Math.abs(car.speed)*3.6);$('auto-distance').textContent=(car.distance/1000).toFixed(2);$('auto-turn').textContent=Math.abs(car.speed)<.05?'N':car.speed<0?'R':'D';if(performance.now()>noticeUntil){const text=paused?'Drive paused. Resume when ready.':'↑ Accelerate · ↓ Brake / reverse · ← → Steer · Space Stop';if($('auto-message').textContent!==text)$('auto-message').textContent=text;}}
 function step(time){if(!active)return;const dt=last?Math.min((time-last)/1000,.2):0;last=time;const pad=gamepad.poll();if(pad.disconnected)pause(true);if(pad.pause)pause(!paused);if(pad.camera)$('auto-camera').click();if(!paused&&dt){const impacts=car.impacts;advanceCar(car,{throttle:Math.max(Number(keys.has('ArrowUp')),pad.throttle),reverse:Math.max(Number(keys.has('ArrowDown')),pad.reverse),steer:clamp(Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft'))+tilt.getSteer()+pad.turn,-1,1),brake:keys.has('Space')||pad.brake},dt,world);speed=car.speed;distance=car.distance;heading=car.heading;wheelAngle=car.wheel;model.front.rotation.z=-car.steer;model.body.rotation.x=car.pitch;model.body.rotation.y=car.roll;if(car.impacts>impacts&&performance.now()>noticeUntil)message('Contact. Brake, then reverse to pull away.');updateCamera(dt);map.triggerRepaint();}updateHUD();raf=requestAnimationFrame(step);}
 map.addLayer({id:'auto-model',type:'custom',renderingMode:'3d',onAdd(m,gl){renderer=new T.WebGLRenderer({canvas:m.getCanvas(),context:gl,antialias:true});renderer.autoClear=false;},render(gl,args){if(!active)return;const p=toLngLat([car.x,car.y]),c=maplibregl.MercatorCoordinate.fromLngLat(p,.02),s=c.meterInMercatorCoordinateUnits(),matrix=new T.Matrix4().makeTranslation(c.x,c.y,c.z).scale(new T.Vector3(s,-s,s));model.group.rotation.z=-heading*Math.PI/180;model.wheels.forEach(w=>w.rotation.x=-wheelAngle);camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(matrix);renderer.resetState();renderer.render(scene,camera);}});
 function exit(){if(!active)return;active=false;tilt.stop();release();cancelAnimationFrame(raf);map.setCenterClampedToGround(true);map.setMaxZoom(oldMax);for(const [key,on]of Object.entries(oldHandlers))if(on)map[key].enable();map.jumpTo(oldCamera);for(const [id,visibility]of oldSymbols)if(map.getLayer(id))map.setLayoutProperty(id,'visibility',visibility);map.setLayoutProperty('auto-road-surface','visibility','none');document.body.classList.remove('auto-active','flight-active');hud.hidden=controls.hidden=true;map.triggerRepaint();document.querySelector('[data-ride=auto]')?.focus();}
 function start(){if(active||window.flightState?.().active)return;stopOrbit();map.stop();oldCamera={center:map.getCenter(),zoom:map.getZoom(),pitch:map.getPitch(),bearing:map.getBearing(),elevation:map.getCenterElevation()};oldMax=map.getMaxZoom();oldHandlers={};for(const key of ['dragPan','dragRotate','scrollZoom','boxZoom','doubleClickZoom','keyboard','touchZoomRotate','touchPitch']){if(map[key]){oldHandlers[key]=map[key].isEnabled();map[key].disable();}}oldSymbols=map.getStyle().layers.filter(l=>l.type==='symbol').map(l=>[l.id,l.layout?.visibility||'visible']);for(const [id]of oldSymbols)map.setLayoutProperty(id,'visibility','none');map.setLayoutProperty('auto-road-surface','visibility','visible');active=true;gamepad.reset();map.setMaxZoom(24);map.setCenterClampedToGround(false);document.body.classList.add('auto-active','flight-active');$('hangar').hidden=true;$('inspector').hidden=true;hud.hidden=controls.hidden=false;reset();last=0;map.getCanvas().focus();raf=requestAnimationFrame(step);}
 $('exit-auto').onclick=exit;$('pause-auto').onclick=()=>pause(!paused);$('reset-auto').onclick=reset;$('auto-camera').onclick=()=>{wide=!wide;$('auto-camera').textContent=wide?'Chase view':'Wide view';updateCamera();map.triggerRepaint();};
 const normal=code=>({KeyW:'ArrowUp',KeyS:'ArrowDown',KeyA:'ArrowLeft',KeyD:'ArrowRight'}[code]||code);
 document.addEventListener('keydown',e=>{if(!active||e.target.matches('input,select,textarea'))return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)pause(!paused);return;}const code=normal(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(code)){e.preventDefault();if(paused)return;keys.add(code);map.getCanvas().focus({preventScroll:true});}});
 document.addEventListener('keyup',e=>keys.delete(normal(e.code)));
 document.querySelectorAll('[data-auto-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(!active||paused)return;b.setPointerCapture(e.pointerId);keys.add(b.dataset.autoKey);b.classList.add('held');});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{keys.delete(b.dataset.autoKey);b.classList.remove('held');});});
 window.addEventListener('blur',()=>{if(active)pause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause(true);});
 window.autoState=()=>({active,paused,speed,distance,heading,choice,wheelAngle,position:car?toLngLat([car.x,car.y]):null,tilt:tilt.state(),gamepad:gamepad.state(),physics:car?{steer:car.steer,yaw:car.yaw,roll:car.roll,pitch:car.pitch,impacts:car.impacts,surface:car.surface}:null,ended:path?.ended,edge:path?.edge,from:path?.from,to:path?.to,progress:path?.progress,roadEdges:graph.edges.length,connectedNodes:graph.connected.size,keys:[...keys]});
 return{start};
}
