import {setMapSceneCamera} from './map-scene-camera.js';
import {addVehicleContactShadow} from './vehicle-contact-shadow.js';
import {installVehicleEnvironment} from './vehicle-environment.js';
import {createBlenderVehicle} from './blender-vehicle.js';
import {loadDrivingData} from './driving-data.js';
import {cbdRoadGraph,nearestRoute,stepRoute} from './npc-traffic.js';
import {applyTrafficDirections} from './traffic-simulation.js';
import {createSupercar} from './supercar-model.js';
import {createTwoWheeler} from './vehicle-models.js';
import {addStreetDetail} from './street-detail.js';
import {createGamepadControls} from './gamepad-controls.js';
import {createTiltControls} from './tilt-controls.js';
import {buildRoadGraph,spawnRoad,roadPosition,advanceRoad,reverseRoad,bearing,angleGap,toLngLat,toLocal} from './auto-roads.js';
import {createCar,advanceCar} from './auto-physics.js';
import {vehicleProfile} from './vehicle-tuning.js';
import {advanceAutoRoam,legalRoamEntry,clearRoadSpawn} from './auto-roam-physics.js';
import {createBoostMeter} from './boost-meter.js';
import {createDrivingWorld} from './auto-world.js';
import {createSpring,advanceSpring} from './flight-physics.js';
let setupPromise;
export function prepareAuto(map){if(!setupPromise)setupPromise=setup(map).catch(e=>{setupPromise=null;throw e;});return setupPromise;}
export async function startAuto(map,vehicleType='auto',departure){const controller=await prepareAuto(map);await controller.start(vehicleType,departure);}
async function setup(map){
 const [T,modelModule,response]=await Promise.all([import('https://unpkg.com/three@0.169.0/build/three.module.js'),import('./auto-model.js'),loadDrivingData()]);const data=response,graph=applyTrafficDirections(buildRoadGraph(data),data),world=createDrivingWorld(data,graph),tourGraph=cbdRoadGraph(data);
 const names={cybertruck:'Cybertruck',cybercab:'Cybercab',kitt:'Knight Rider',auto:'Auto',supercar:'Supercar',yulu:'Yulu-style e-bike',bike:'Rapido-style bike',delivery:'Delivery bike',cycle:'Cycle'};let vehicleType='auto',departurePoint;const models={auto:modelModule.createAuto(T)};let model=models.auto;const scene=new T.Scene(),camera=new T.Camera();scene.add(model.group,new T.HemisphereLight(0xcde6ed,0x766653,2.1));const sun=new T.DirectionalLight(0xfff0d4,2.5);sun.position.set(-20,-30,60);scene.add(sun);
 const staticCollision=world.collide;world.collide=(x,y,heading)=>window.npcTrafficCollider?.(x,y,heading,vehicleType)||staticCollision(x,y,heading);
 await model.ready;window.addEventListener('vehicle-color-change',e=>model.setPaint?.(e.detail?.color));
 // Metre-width surfaces remain readable when zoomed beyond the basemap style.
 const roads={type:'FeatureCollection',features:graph.edges.map(e=>{const a=graph.nodes[e.a].p,b=graph.nodes[e.b].p,w=e.width?e.width/2:({service:2.5,minor:3.5,tertiary:5,secondary:6,primary:7,trunk:8}[e.kind]||3.5),dx=(b[0]-a[0])/e.length,dy=(b[1]-a[1])/e.length;const ring=[[a[0]-dy*w-dx*.3,a[1]+dx*w-dy*.3],[b[0]-dy*w+dx*.3,b[1]+dx*w+dy*.3],[b[0]+dy*w+dx*.3,b[1]-dx*w+dy*.3],[a[0]+dy*w-dx*.3,a[1]-dx*w-dy*.3]];ring.push(ring[0]);return{type:'Feature',properties:{vidhana:Math.hypot((a[0]+b[0])/2-toLocal([77.5908,12.9798])[0],(a[1]+b[1])/2-toLocal([77.5908,12.9798])[1])<488},geometry:{type:'Polygon',coordinates:[ring.map(toLngLat)]}}})};
 map.addSource('auto-roads',{type:'geojson',data:roads});map.addLayer({id:'auto-road-surface',type:'fill',source:'auto-roads',filter:['!=',['get','vidhana'],true],layout:{visibility:'none'},paint:{'fill-color':'#555c59','fill-antialias':false}},'district-detail');
 const streetDetail=addStreetDetail(map,graph,data);window.raiseVidhanaStreets?.();
 let roaming=false,tourPath;let car,cameraRig,lookRig;function groundHeight(){if(!car)return 0;const a=car.heading*Math.PI/180,half=(car.profile?.wheelbase||1.6)/2;return Math.max(...[-half,0,half].map(d=>(window.vidhanaStreetPatch?.heightAt(...toLngLat([car.x+Math.sin(a)*d,car.y+Math.cos(a)*d]))??streetDetail.heightAt(car.x+Math.sin(a)*d,car.y+Math.cos(a)*d))));}let orbitYaw=0,orbitElevation=12,orbitDistance=13,dragPointer=null,dragX=0,dragY=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const keys=new Set();let active=false,paused=false,path,speed=0,distance=0,heading=0,choice='straight',last=0,raf=0,wheelAngle=0,oldCamera,oldMax,oldHandlers,oldSymbols=[],wide=false,renderer,noticeUntil=0;
 const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
 const hud=document.createElement('section');hud.id='auto-hud';hud.hidden=true;hud.innerHTML=`<div class="flight-top"><div><span class="sub">BENGALURU / AUTO</span><strong>CBD drive</strong></div><button id="exit-auto">Exit drive</button></div><div class="instruments"><div><strong id="auto-speed">0</strong><span>km/h</span></div><div><strong id="auto-distance">0.00</strong><span>km driven</span></div><div><strong id="auto-turn">N</strong><span>gear</span></div></div><div class="flight-actions"><button id="pause-auto">Pause</button><button id="auto-camera">Wide view</button><button id="reset-auto">Reset auto</button></div><p id="auto-message" role="status" aria-live="polite">↑ Accelerate · ↓ Brake / reverse · ← → Steer · Space Stop</p><span class="sub">Free steering · CBD · Arcade vehicle physics</span>`;document.body.appendChild(hud);
 const controls=document.createElement('section');controls.id='auto-controls';controls.hidden=true;controls.innerHTML=`<div class="auto-turn-controls"><button data-auto-key="ArrowLeft" aria-label="Steer left">← Steer</button><button data-auto-key="Space">Stop</button><button data-auto-key="ArrowRight" aria-label="Steer right">Steer →</button></div><div class="auto-pedals"><button data-auto-key="ShiftLeft" aria-label="Hold to boost">Boost</button><button data-auto-key="ArrowDown">↓ Brake / reverse</button><button data-auto-key="ArrowUp" class="primary">↑ Accelerate</button></div>`;document.body.appendChild(controls);
 const boostMeter=createBoostMeter(hud);
 const gamepad=createGamepadControls(hud,'auto');
 const tilt=createTiltControls(hud,()=>active&&!paused);
 function message(text){$('auto-message').textContent=text;noticeUntil=performance.now()+4000;}
 function release(){if(car?.boost)car.boost.active=false;dragPointer=null;keys.clear();document.querySelectorAll('[data-auto-key]').forEach(b=>b.classList.remove('held'));}
 function pause(value){paused=value;release();last=0;$('pause-auto').textContent=paused?'Resume':'Pause';message(paused?'Drive paused. Resume when ready.':'Controls active.');}
 function updateCamera(dt=0){
  if(window.domeOverview){window.applyDomeOverview?.();return;}
  const a=(car.heading+orbitYaw)*Math.PI/180,elevation=orbitElevation*Math.PI/180,scale=innerWidth<761?1.35:1,radius=orbitDistance*scale,horizontal=radius*Math.cos(elevation);
  const target={x:car.x-Math.sin(a)*horizontal,y:car.y-Math.cos(a)*horizontal,z:1.5+radius*Math.sin(elevation)},look={x:car.x,y:car.y,z:1.5};
  if(!cameraRig||!dt||reduced||dragPointer!==null){cameraRig=createSpring(target.x,target.y,target.z);lookRig=createSpring(look.x,look.y,look.z);}else{advanceSpring(cameraRig,target,dt,5);advanceSpring(lookRig,look,dt,9);}
  map.jumpTo(map.calculateCameraOptionsFromTo(toLngLat([cameraRig.x,cameraRig.y]),cameraRig.z,toLngLat([lookRig.x,lookRig.y]),lookRig.z));
 }
 function reset(){roaming=false;orbitYaw=0;orbitElevation=12;orbitDistance=13;window.setDomeOverview?.(false);path=spawnRoad(graph,departurePoint?toLocal(departurePoint):undefined);const spawn=clearRoadSpawn(graph,path,(x,y,h)=>window.npcTrafficCollider?.(x,y,h,vehicleType));if(!spawn)throw new Error('Departure lane is occupied. Choose another departure or retry shortly.');path=spawn.path;car=createCar(spawn.point[0],spawn.point[1],spawn.heading);car.profile=vehicleProfile(vehicleType);if(model.wheelRadius)car.profile.wheelRadius=model.wheelRadius;speed=distance=wheelAngle=0;heading=car.heading;cameraRig=lookRig=null;pause(false);updateCamera();message('↑ Accelerate · ↓ Brake / reverse · ← → Steer · Space Stop');map.triggerRepaint();}
 function updateHUD(){ boostMeter(car.boost,roaming);$('auto-speed').textContent=Math.round(Math.abs(car.speed)*3.6);$('auto-distance').textContent=(car.distance/1000).toFixed(2);$('auto-turn').textContent=Math.abs(car.speed)<.05?'N':car.speed<0?'R':'D';if(performance.now()>noticeUntil){const text=paused?'Drive paused. Resume when ready.':'↑ Accelerate · ↓ Brake / reverse · ← → Steer · Space Stop';if($('auto-message').textContent!==text)$('auto-message').textContent=text;}}
 function step(time){if(!active)return;const dt=last?Math.min((time-last)/1000,.2):0;last=time;const pad=gamepad.poll(),touch=window.mobileDriveInput?.()||{},touchThrottle=clamp(Number(touch.throttle)||0,0,1),touchReverse=clamp(Number(touch.reverse)||0,0,1),touchSteer=clamp(Number(touch.steer)||0,-1,1);if(pad.disconnected)pause(true);if(pad.pause)pause(!paused);if(pad.camera)$('auto-camera').click();if(!paused&&dt){const impacts=car.impacts;if(roaming&&(keys.size||touchThrottle>.15||touchReverse>.15||Math.abs(touchSteer)>.15||pad.throttle>.15||pad.reverse>.15||Math.abs(pad.turn)>.15||pad.brake||pad.boost||Math.abs(tilt.getSteer())>.2))roaming=false;if(roaming){car.boost.active=false;const priorHeading=car.heading,state=advanceAutoRoam(tourGraph,tourPath,car,dt,(x,y,h)=>window.npcTrafficCollider?.(x,y,h,vehicleType));tourPath=state.path;car.yaw=angleGap(car.heading,priorHeading)*Math.PI/180/Math.max(dt,.001);car.steer=Math.atan(car.yaw*car.profile.wheelbase/Math.max(1,car.speed));car.pitch=0;car.roll=clamp(-car.speed*car.yaw*car.profile.rollGain,-car.profile.maxLean,car.profile.maxLean);}else advanceCar(car,{throttle:Math.max(Number(keys.has('ArrowUp')),pad.throttle,touchThrottle),reverse:Math.max(Number(keys.has('ArrowDown')),pad.reverse,touchReverse),steer:clamp(Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft'))+tilt.getSteer()+pad.turn+touchSteer,-1,1),boost:keys.has('ShiftLeft')||pad.boost,brake:keys.has('Space')||pad.brake},dt,world);speed=car.speed;distance=car.distance;heading=car.heading;wheelAngle=car.wheel;model.front.rotation.z=-car.steer;model.body.rotation.x=car.pitch;model.body.rotation.y=car.roll;if(car.impacts>impacts&&performance.now()>noticeUntil)message('Contact. Brake, then reverse to pull away.');updateCamera(dt);map.triggerRepaint();}updateHUD();raf=requestAnimationFrame(step);}
 map.addLayer({id:'auto-model',type:'custom',renderingMode:'3d',onAdd(m,gl){renderer=new T.WebGLRenderer({canvas:m.getCanvas(),context:gl,antialias:true});renderer.autoClear=false;installVehicleEnvironment(T,renderer,scene);renderer.compile(scene,camera);renderer.resetState();},render(gl,args){if(!active)return;const p=toLngLat([car.x,car.y]),c=maplibregl.MercatorCoordinate.fromLngLat(p,groundHeight()+.02),s=c.meterInMercatorCoordinateUnits(),matrix=new T.Matrix4().makeTranslation(c.x,c.y,c.z).scale(new T.Vector3(s,-s,s));model.group.rotation.z=-heading*Math.PI/180;if(model.updateDrive)model.updateDrive(wheelAngle,car.steer,performance.now()/1000);else model.wheels.forEach(w=>w.rotation.x=-wheelAngle);if(model.pedals)model.pedals.rotation.x=-wheelAngle*.4;model.updateRider?.(-wheelAngle*.4);camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(matrix);setMapSceneCamera(T,camera,camera.projectionMatrix);renderer.resetState();{const submitStart=performance.now();renderer.render(scene,camera);window.recordCityRender?.('Auto',renderer,performance.now()-submitStart);}}});
 function exit(){if(!active)return;window.setDomeOverview?.(false);active=false;tilt.stop();release();cancelAnimationFrame(raf);map.setCenterClampedToGround(true);map.setMaxZoom(oldMax);for(const [key,on]of Object.entries(oldHandlers))if(on)map[key].enable();map.jumpTo(oldCamera);for(const [id,visibility]of oldSymbols)if(map.getLayer(id))map.setLayoutProperty(id,'visibility',visibility);map.setLayoutProperty('auto-road-surface','visibility','none');streetDetail.setVisible(false);document.body.classList.remove('auto-active','flight-active');hud.hidden=controls.hidden=true;map.triggerRepaint();document.querySelector('[data-ride='+vehicleType+']')?.focus();}
 async function start(type='auto',departure){if(active||window.flightState?.().active)return;if(!names[type])throw Error('Unsupported vehicle');vehicleType=type;departurePoint=departure;if(!models[type])models[type]=['cybertruck','cybercab','kitt'].includes(type)?await createBlenderVehicle(T,type):type==='supercar'?createSupercar(T):createTwoWheeler(T,{variant:type});await models[type].ready;addVehicleContactShadow(T,models[type].group);if(model!==models[type]){model.group.visible=false;model=models[type];if(!model.group.parent)scene.add(model.group);model.group.visible=true;}hud.querySelector('.flight-top .sub').textContent='BENGALURU / '+names[type].toUpperCase();$('reset-auto').textContent='Reset '+names[type];stopOrbit();map.stop();oldCamera={center:map.getCenter(),zoom:map.getZoom(),pitch:map.getPitch(),bearing:map.getBearing(),elevation:map.getCenterElevation()};oldMax=map.getMaxZoom();oldHandlers={};for(const key of ['dragPan','dragRotate','scrollZoom','boxZoom','doubleClickZoom','keyboard','touchZoomRotate','touchPitch']){if(map[key]){oldHandlers[key]=map[key].isEnabled();map[key].disable();}}oldSymbols=map.getStyle().layers.filter(l=>l.type==='symbol').map(l=>[l.id,l.layout?.visibility||'visible']);for(const [id]of oldSymbols)map.setLayoutProperty(id,'visibility','none');map.setLayoutProperty('auto-road-surface','visibility','visible');streetDetail.setVisible(true);active=true;gamepad.reset();map.setMaxZoom(24);map.setCenterClampedToGround(false);document.body.classList.add('auto-active','flight-active');$('hangar').hidden=true;$('inspector').hidden=true;hud.hidden=controls.hidden=false;reset();last=0;map.getCanvas().focus();raf=requestAnimationFrame(step);}
 $('exit-auto').onclick=exit;$('pause-auto').onclick=()=>pause(!paused);$('reset-auto').onclick=reset;$('auto-camera').onclick=()=>{window.setDomeOverview?.(false);wide=!wide;orbitYaw=0;orbitElevation=wide?30:12;orbitDistance=wide?24:13;$('auto-camera').textContent=wide?'Chase view':'Wide view';updateCamera();map.triggerRepaint();};
 window.addEventListener('cbd-overview-change',()=>{if(active&&car&&!window.domeOverview){updateCamera();map.triggerRepaint();}});
 const canvas=map.getCanvas();
 canvas.addEventListener('pointerdown',e=>{if(!active||e.button!==0)return;e.preventDefault();window.setDomeOverview?.(false);dragPointer=e.pointerId;dragX=e.clientX;dragY=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';});
 canvas.addEventListener('pointermove',e=>{if(!active||dragPointer!==e.pointerId)return;orbitYaw=(orbitYaw-(e.clientX-dragX)*.35)%360;orbitElevation=clamp(orbitElevation+(e.clientY-dragY)*.25,6,75);dragX=e.clientX;dragY=e.clientY;updateCamera();map.triggerRepaint();});
 for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{if(e.pointerId===dragPointer){dragPointer=null;canvas.style.cursor='';}});
 canvas.addEventListener('wheel',e=>{if(!active)return;e.preventDefault();window.setDomeOverview?.(false);orbitDistance=clamp(orbitDistance*Math.exp(clamp(e.deltaY,-150,150)*.003),6,65);updateCamera();map.triggerRepaint();},{passive:false});
 const normal=code=>({ShiftRight:'ShiftLeft',KeyW:'ArrowUp',KeyS:'ArrowDown',KeyA:'ArrowLeft',KeyD:'ArrowRight'}[code]||code);
 document.addEventListener('keydown',e=>{if(!active||e.target.matches('input,select,textarea'))return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)pause(!paused);return;}const code=normal(e.code);if(['ShiftLeft','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(code)){e.preventDefault();if(paused)return;keys.add(code);map.getCanvas().focus({preventScroll:true});}});
 document.addEventListener('keyup',e=>keys.delete(normal(e.code)));
 document.querySelectorAll('[data-auto-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(!active||paused)return;b.setPointerCapture(e.pointerId);keys.add(b.dataset.autoKey);b.classList.add('held');});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>{keys.delete(b.dataset.autoKey);b.classList.remove('held');});});
 window.addEventListener('blur',()=>{if(active)pause(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)pause(true);});
 window.autoCameraControls={orbit(dx,dy){if(!active)return;window.setDomeOverview?.(false);orbitYaw=(orbitYaw+dx)%360;orbitElevation=clamp(orbitElevation+dy,6,75);updateCamera();map.triggerRepaint();}};
 document.addEventListener('keydown',e=>{if(active&&!e.target.matches('input,select,textarea')&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft'].includes(e.code))roaming=false;},true);
 window.setAutoRoam=value=>{if(!active)return false;if(value){const nearest=nearestRoute(tourGraph,[car.x,car.y]);if(!nearest.path||nearest.distance>4){message('Move onto a CBD road to start auto-roam.');return false;}const entry=legalRoamEntry(tourGraph,nearest.path,car.heading);if(!entry){message('Face the legal direction of this road before starting auto-roam.');return false;}tourPath=entry;delete car.roamJoin;pause(false);}roaming=!!value;return roaming;};
 window.autoState=()=>({vehicleType,visualHeight:model.group.userData.visualHeight,roaming,groundHeight:groundHeight(),cameraOrbit:{yaw:orbitYaw,elevation:orbitElevation,distance:orbitDistance},active,paused,boost:car?{...car.boost}:null,speed,distance,heading,choice,wheelAngle,position:car?toLngLat([car.x,car.y]):null,tilt:tilt.state(),gamepad:gamepad.state(),physics:car?{steer:car.steer,yaw:car.yaw,roll:car.roll,pitch:car.pitch,impacts:car.impacts,surface:car.surface}:null,ended:path?.ended,edge:path?.edge,from:path?.from,to:path?.to,progress:path?.progress,roadEdges:graph.edges.length,connectedNodes:graph.connected.size,keys:[...keys]});
 return{start};
}






