/* Arcade flight in local metres; the map and aircraft share a WebGL context. */
(() => {
 const el=id=>document.getElementById(id);
 const pads=[{name:'Cubbon departure',lng:77.592,lat:12.9745},{name:'Cubbon north',lng:77.5928,lat:12.9762}];
 const keys=new Set();const RAD=Math.PI/180;const METRES=111320;
 let roaming=false,tourIndex=0;const tour=[[77.592,12.9745],[77.597,12.973],[77.598,12.978],[77.592,12.979]];
 let active=false,paused=false,phase='parked',raf=0,last=0,THREE,layer,loading=false,oldCamera,oldHandlers,alt=2,lng=pads[0].lng,lat=pads[0].lat,heading=0,speed=0,side=0,rotorAngle=0,selectedPad=0,travel=0,cameraMode='chase',cameraHeading=0,flightNotice='',noticeUntil=0;
 let cameraOrbitYaw=0,cameraOrbitLift=0;let tilt,gamepad;let oldSymbols=[],boundary,mouse={id:null,x:0,y:0,turn:0,forward:0},wheelLift=0,wheelUntil=0;let dynamics,physics,craft,cameraRig,lookRig,rotorPower=0,oldMaxZoom;
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const gap=(a,b)=>((a-b+540)%360)-180;
 const distance=p=>Math.hypot((p.lng-lng)*METRES*Math.cos(lat*RAD),(p.lat-lat)*METRES);
 const nearest=()=>pads.reduce((best,p)=>distance(p)<distance(best)?p:best,pads[0]);
 const offset=(x,y)=>[lng+x/(METRES*Math.cos(lat*RAD)),lat+y/METRES];
 function notice(text){flightNotice=text;noticeUntil=performance.now()+4000;el('flight-message').textContent=text;}
 function release(){window.dispatchEvent(new Event('opencity:release-input'));if(dynamics?.boost)dynamics.boost.active=false;mouse.id=null;mouse.turn=mouse.forward=0;wheelLift=0;keys.clear();if(map)map.getCanvas().style.cursor="";document.querySelectorAll('[data-flight-key]').forEach(b=>b.classList.remove('held'));}
 function setPaused(value){if(!active)return;paused=value;release();last=0;el('pause-flight').textContent=paused?'Resume':'Pause';el('pause-flight').setAttribute('aria-pressed',String(paused));notice(paused?'Flight paused. Resume when ready.':'Controls active.');}
 function padFeature(p){const ring=[];for(let i=0;i<=48;i++){const a=i/48*Math.PI*2;ring.push([p.lng+22*Math.cos(a)/(METRES*Math.cos(p.lat*RAD)),p.lat+22*Math.sin(a)/METRES]);}return{type:'Feature',properties:{name:p.name},geometry:{type:'Polygon',coordinates:[ring]}};}
 let preparePromise,boostModule,boostMeter,setMapSceneCamera;
 function ensureLayer(){if(!preparePromise)preparePromise=buildLayer().catch(e=>{preparePromise=null;throw e;});return preparePromise;}window.prepareHelicopter=ensureLayer;
 async function buildLayer(){
  if(layer)return;
  const modules=await Promise.all([import('https://unpkg.com/three@0.169.0/build/three.module.js'),import('./flight-physics.js'),import('./helicopter.js'),import('./cbd-boundary.js'),import('./tilt-controls.js'),import('./gamepad-controls.js'),import('./vehicle-boost.js'),import('./boost-meter.js'),import('./map-scene-camera.js')]);
  setMapSceneCamera=modules[8].setMapSceneCamera;
  boostModule=modules[6];boostMeter=modules[7].createBoostMeter(el('flight-hud'));gamepad=modules[5].createGamepadControls(el('flight-hud'),'flight');THREE=modules[0];physics=modules[1];boundary=modules[3];tilt=modules[4].createTiltControls(el('flight-hud'),()=>active&&!paused);craft=modules[2].createHelicopter(THREE);dynamics=physics.createDynamics();
  layer={id:'helicopter-model',type:'custom',renderingMode:'3d',
   onAdd(map,gl){this.camera=new THREE.Camera();this.scene=new THREE.Scene();this.scene.add(craft.group);this.scene.add(new THREE.HemisphereLight(0xffffff,0x688471,2.4));const sun=new THREE.DirectionalLight(0xffefd5,3);sun.position.set(-50,30,100);this.scene.add(sun);this.renderer=new THREE.WebGLRenderer({canvas:map.getCanvas(),context:gl,antialias:true});this.renderer.autoClear=false;this.renderer.compile(this.scene,this.camera);this.renderer.resetState();},
   render(gl,args){if(!active)return;const c=maplibregl.MercatorCoordinate.fromLngLat([lng,lat],alt);const s=c.meterInMercatorCoordinateUnits();const transform=new THREE.Matrix4().makeTranslation(c.x,c.y,c.z).scale(new THREE.Vector3(s,-s,s));craft.group.rotation.z=-heading*RAD;craft.body.rotation.set(dynamics.pitch,dynamics.roll,0,'YXZ');craft.rotor.rotation.z=rotorAngle;craft.tailRotor.rotation.x=-rotorAngle*3.7;craft.rotorDisc.material.opacity=rotorPower*.085;this.camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);setMapSceneCamera(THREE,this.camera,this.camera.projectionMatrix);this.renderer.resetState();{const submitStart=performance.now();this.renderer.render(this.scene,this.camera);window.recordCityRender?.('Helicopter',this.renderer,performance.now()-submitStart);}},
   onRemove(){this.scene.traverse(o=>{o.geometry?.dispose();if(o.material)o.material.dispose();});this.renderer.dispose();}
  };
  map.addSource('flight-pads',{type:'geojson',data:{type:'FeatureCollection',features:pads.map(padFeature)}});
  map.addLayer({id:'flight-pads',type:'fill',source:'flight-pads',layout:{visibility:'none'},paint:{'fill-color':'#ecaa3d','fill-opacity':.85}});
  map.addSource('flight-pad-labels',{type:'geojson',data:{type:'FeatureCollection',features:pads.map(p=>({type:'Feature',properties:{name:'H · '+p.name},geometry:{type:'Point',coordinates:[p.lng,p.lat]}}))}});
  map.addLayer({id:'flight-pad-labels',type:'symbol',source:'flight-pad-labels',layout:{visibility:'none','text-field':['get','name'],'text-font':['Noto Sans Regular'],'text-size':14,'text-offset':[0,2],'text-allow-overlap':true},paint:{'text-color':'#18302d','text-halo-color':'#f4f7f3','text-halo-width':2}});
  map.addLayer(layer);
 }
 function camera(dt=1,snap=false){
  if(window.domeOverview){window.applyDomeOverview?.();return;}
  if(cameraMode==='shield'){map.jumpTo({center:[77.5945,12.9755],zoom:14.8,pitch:55,bearing:-25});return;}
  const origin=pads[selectedPad],cos=Math.cos(origin.lat*RAD);
  const x=(lng-origin.lng)*METRES*cos,y=(lat-origin.lat)*METRES;
  const a=(heading+cameraOrbitYaw)*RAD,velocity=Math.hypot(dynamics.vx,dynamics.vy);
  const overhead=cameraMode==='overhead';
  const framing=innerWidth<761?1.25:1; const behind=overhead?8:(48+velocity*.45)*framing,shoulder=overhead?0:12;
  const desired={x:x-Math.sin(a)*behind+Math.cos(a)*shoulder,y:y-Math.cos(a)*behind-Math.sin(a)*shoulder,z:alt+(overhead?180:(23+velocity*.12)*framing+cameraOrbitLift)};
  const look={x:x+Math.sin(a)*5,y:y+Math.cos(a)*5,z:alt+3.4};
  if(!cameraRig||snap||reduced){cameraRig=physics.createSpring(desired.x,desired.y,desired.z);lookRig=physics.createSpring(look.x,look.y,look.z);}
  else{physics.advanceSpring(cameraRig,desired,dt,5.2);physics.advanceSpring(lookRig,look,dt,10);}
  const position=[origin.lng+cameraRig.x/(METRES*cos),origin.lat+cameraRig.y/METRES];
  const target=[origin.lng+lookRig.x/(METRES*cos),origin.lat+lookRig.y/METRES];
  map.jumpTo(map.calculateCameraOptionsFromTo(position,Math.max(cameraRig.z,alt+16),target,lookRig.z));
 }
 function reset(){roaming=false;window.setDomeOverview?.(false);release();const p=pads[selectedPad];lng=p.lng;lat=p.lat;alt=2;heading=0;speed=0;side=0;travel=0;phase='parked';cameraHeading=0;cameraOrbitYaw=cameraOrbitLift=0;paused=false;dynamics=physics.createDynamics();cameraRig=lookRig=null;rotorPower=0;rotorAngle=0;el('pause-flight').textContent='Pause';el('pause-flight').setAttribute('aria-pressed','false');camera();notice('On virtual pad. Press Take off to begin.');updateHUD();}
 function takeoff(){if(paused)return;if(phase==='parked'){phase='takeoff';notice('Climbing to 90 m. Steering unlocks at cruise height.');}else if(phase==='flying'){const pad=nearest();if(distance(pad)>35||Math.abs(speed)>8||Math.abs(side)>4){notice('To land: approach a pad within 35 m and slow below 29 km/h.');return;}selectedPad=pads.indexOf(pad);phase='landing';speed=side=0;dynamics.vx=dynamics.vy=dynamics.vz=0;release();notice('Landing on '+pad.name+'.');}}
 function updateHUD(){boostMeter?.(dynamics?.boost,roaming);el('flight-speed').textContent=Math.round(Math.hypot(speed,side)*3.6);el('flight-altitude').textContent=Math.round(alt-2);el('flight-heading').textContent=String(Math.round((heading+360)%360)).padStart(3,'0')+'°';el('flight-distance').textContent=(travel/1000).toFixed(2);el('flight-phase').textContent=paused?'Paused':({parked:'On pad',takeoff:'Taking off',flying:'Free flight',landing:'Landing'})[phase];el('takeoff').textContent=phase==='parked'?'Take off':phase==='flying'?'Land on pad':phase==='takeoff'?'Taking off…':'Landing…';el('takeoff').disabled=paused||phase==='takeoff'||phase==='landing';const p=nearest();el('pad-distance').textContent=`${p.name} · ${(distance(p)/1000).toFixed(2)} km`;if(performance.now()>noticeUntil){const message=paused?'Flight paused. Resume when ready.':phase==='flying'?'Arrows fly · Drag mouse to steer · Q/E altitude · Space hover':phase==='parked'?'Ready on virtual pad. Select Take off.':phase==='takeoff'?'Automatic climb to 90 m.':'Automatic pad approach.';if(el('flight-message').textContent!==message)el('flight-message').textContent=message;}}
 function step(t){if(!active)return;const dt=last?Math.min((t-last)/1000,.2):0;last=t;const pad=gamepad.poll();if(pad.disconnected)setPaused(true);if(pad.pause)setPaused(!paused);if(pad.camera)el('camera-flight').click();if(pad.takeoff)takeoff();
  if(!paused&&dt){
   rotorPower+=((phase==='parked'?.12:1)-rotorPower)*(1-Math.exp(-dt*1.7));
   // Deliberately readable blade cadence; the blur disk conveys faster rotation.
   // Rotor motion is functional feedback and explicitly requested, including in reduced motion.
   rotorAngle=(rotorAngle+dt*(4+rotorPower*17))%(Math.PI*2);
   if(phase==='takeoff'&&rotorPower>.72){alt=Math.min(92,alt+22*dt);if(alt>=92)phase='flying';}
   if(phase==='landing'){const p=pads[selectedPad];lng+=(p.lng-lng)*Math.min(1,dt*3);lat+=(p.lat-lat)*Math.min(1,dt*3);alt=Math.max(2,alt-18*dt);dynamics.pitch*=Math.exp(-dt*4);dynamics.roll*=Math.exp(-dt*4);if(alt===2){lng=p.lng;lat=p.lat;phase='parked';const reserve=dynamics.boost;dynamics=physics.createDynamics();dynamics.boost=reserve;dynamics.heading=heading;notice('Landed. Explore another route when ready.');}}
   if(phase==='flying'){
    const touch=window.mobileDriveInput?.()||{};const input={forward:clamp(Number(keys.has('ArrowUp'))-Number(keys.has('ArrowDown'))+mouse.forward+pad.forward+(Number(touch.throttle)||0)-(Number(touch.reverse)||0),-1,1),turn:clamp(Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft'))+mouse.turn+(tilt?.getSteer()||0)+pad.turn+(Number(touch.steer)||0),-1,1),strafe:0,vertical:clamp(Number(keys.has('KeyE'))-Number(keys.has('KeyQ'))+(performance.now()<wheelUntil?wheelLift:0)+pad.vertical,-1,1),boost:keys.has('ShiftLeft')||pad.boost,brake:keys.has('Space')||pad.brake};
    if(roaming&&(keys.size||Math.abs(input.forward)>.1||Math.abs(input.turn)>.1||Math.abs(input.vertical)>.1||input.brake||input.boost))roaming=false;if(roaming){let target=tour[tourIndex],dx=(target[0]-lng)*METRES*Math.cos(lat*RAD),dy=(target[1]-lat)*METRES;if(Math.hypot(dx,dy)<65){tourIndex=(tourIndex+1)%tour.length;target=tour[tourIndex];dx=(target[0]-lng)*METRES*Math.cos(lat*RAD);dy=(target[1]-lat)*METRES;}const turn=gap(Math.atan2(dx,dy)/RAD,heading),range=Math.hypot(dx,dy);input.turn=clamp(turn/55,-.8,.8);input.forward=1;input.cruiseSpeed=Math.min(85,Math.max(18,85-Math.max(0,Math.abs(turn)-8)*1.25),Math.sqrt(Math.max(65,range)*14));input.vertical=clamp((120-alt)/45,-.45,.45);}
    const movement=physics.advanceDynamics(dynamics,input,dt,{automatic:roaming});heading=dynamics.heading;
    const next=offset(movement.dx,movement.dy),bounded=boundary.domeLimit(next[0],next[1],alt+movement.dz);
    if(bounded.hit){const n=bounded.normal,dot=dynamics.vx*n[0]+dynamics.vy*n[1]+dynamics.vz*n[2];if(dot>0){dynamics.vx-=dot*1.08*n[0];dynamics.vy-=dot*1.08*n[1];dynamics.vz-=dot*1.08*n[2];}if(performance.now()>noticeUntil)notice('CBD shield boundary. Turn back into the city.');}
    const moved=Math.hypot((bounded.lng-lng)*METRES*Math.cos(lat*RAD),(bounded.lat-lat)*METRES);travel+=moved;if(!roaming)boostModule.earnBoost(dynamics.boost,moved,{boostChargePerMetre:.12},movement.boosted);lng=bounded.lng;lat=bounded.lat;alt=bounded.alt;
    const a=heading*RAD;speed=dynamics.vx*Math.sin(a)+dynamics.vy*Math.cos(a);side=dynamics.vx*Math.cos(a)-dynamics.vy*Math.sin(a);
   }
   camera(dt);map.triggerRepaint();
  }
  updateHUD();raf=requestAnimationFrame(step);
 }
 async function start(){if(loading||active||!ready)return;loading=true;el('start-flight').disabled=true;el('start-flight').textContent='Preparing aircraft…';
  try{await ensureLayer();stopOrbit();map.stop();oldCamera={center:map.getCenter(),zoom:map.getZoom(),pitch:map.getPitch(),bearing:map.getBearing(),elevation:map.getCenterElevation()};oldHandlers={};for(const k of ['dragPan','dragRotate','scrollZoom','boxZoom','doubleClickZoom','keyboard','touchZoomRotate','touchPitch']){if(map[k]){oldHandlers[k]=map[k].isEnabled();map[k].disable();}}
   oldSymbols=map.getStyle().layers.filter(l=>l.type==='symbol').map(l=>[l.id,l.layout?.visibility||'visible']);for(const [id]of oldSymbols)map.setLayoutProperty(id,'visibility','none');selectedPad=Number(el('departure-pad').value);active=true;gamepad.reset();el('flight-mouse-tip').hidden=false;oldMaxZoom=map.getMaxZoom();map.setMaxZoom(22);map.setCenterClampedToGround(false);document.body.classList.add('flight-active');el('hangar').hidden=true;el('flight-hud').hidden=false;el('flight-controls').hidden=false;el('inspector').hidden=true;map.setLayoutProperty('flight-pads','visibility','visible');map.setLayoutProperty('flight-pad-labels','visibility','none');reset();map.getCanvas().focus();last=0;raf=requestAnimationFrame(step);
  }catch(e){console.error(e);el('hangar-error').textContent='Aircraft could not load. Check your connection and try again.';}finally{loading=false;el('start-flight').disabled=false;el('start-flight').textContent='Enter helicopter';}
 }
 function exit(){if(!active)return;active=false;tilt?.stop();release();cancelAnimationFrame(raf);map.setCenterClampedToGround(true);map.setMaxZoom(oldMaxZoom);for(const [k,on]of Object.entries(oldHandlers))if(on)map[k].enable();map.jumpTo(oldCamera);for(const id of ['flight-pads','flight-pad-labels'])map.setLayoutProperty(id,'visibility','none');for(const [id,visibility]of oldSymbols)if(map.getLayer(id))map.setLayoutProperty(id,'visibility',visibility);el('flight-mouse-tip').hidden=true;document.body.classList.remove('flight-active');el('flight-hud').hidden=true;el('flight-controls').hidden=true;status('Explore the city · Building heights are schematic');map.triggerRepaint();document.querySelector('[data-ride=helicopter]')?.focus();}
 function init(){
  const garage=document.createElement('section');garage.id='hangar';garage.hidden=true;garage.setAttribute('aria-label','Choose your aircraft');garage.innerHTML=`<button id="close-hangar" class="close" aria-label="Close vehicle selection">×</button><span class="sub">EXPLORE FROM ABOVE</span><h2>Your city. Your ride.</h2><p>Fly a utility helicopter with banking, momentum and a spring-follow chase camera.</p><label for="vehicle">Choose a vehicle</label><select id="vehicle"><option value="helicopter">Helicopter · ready to fly</option><option value="auto">Auto · ready to drive</option><option disabled>Bike · not built yet</option><option disabled>Cab · not built yet</option><option disabled>Bus · not built yet</option><option disabled>Plane · not built yet</option></select><label for="departure-pad">Departure</label><select id="departure-pad">${pads.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('')}</select><p class="note">Arcade flight, virtual landing pads, flat terrain. Altitude is above the model ground. No obstacle collisions.</p><button id="start-flight" class="primary">Enter helicopter</button><p id="hangar-error" role="alert"></p>`;document.body.appendChild(garage);
  const hud=document.createElement('section');hud.id='flight-hud';hud.hidden=true;hud.setAttribute('aria-label','Flight instruments');hud.innerHTML=`<div class="flight-top"><div><span class="sub">BENGALURU / HELICOPTER</span><strong id="flight-phase">On pad</strong></div><button id="exit-flight">Exit flight</button></div><div class="instruments"><div><strong id="flight-speed">0</strong><span>km/h</span></div><div><strong id="flight-altitude">0</strong><span>m altitude</span></div><div><strong id="flight-heading">000°</strong><span>heading</span></div><div><strong id="flight-distance">0.00</strong><span>km flown</span></div></div><div class="flight-actions"><button id="takeoff" class="primary">Take off</button><button id="pause-flight" aria-pressed="false">Pause</button><button id="camera-flight">Overhead view</button><button id="reset-flight">Reset to pad</button></div><p id="flight-message" role="status" aria-live="polite">Ready on virtual pad.</p><span id="pad-distance"></span><span class="flight-note">Virtual pads · No obstacle collisions</span>`;document.body.appendChild(hud);
  const controls=document.createElement('section');controls.id='flight-controls';controls.hidden=true;controls.setAttribute('aria-label','Flight movement controls');controls.innerHTML=`<div class="direction-controls"><button data-flight-key="ArrowUp" aria-label="Fly forward">Forward</button><div><button data-flight-key="ArrowLeft" aria-label="Turn left">↶ Left</button><button data-flight-key="Space" aria-label="Brake to hover">Hover</button><button data-flight-key="ArrowRight" aria-label="Turn right">Right ↷</button></div><button data-flight-key="ArrowDown" aria-label="Fly backward">Back</button></div><div class="height-controls"><button data-flight-key="ShiftLeft" aria-label="Hold to boost">Boost</button><button data-flight-key="KeyE" aria-label="Increase altitude">↑ Rise</button><button data-flight-key="KeyQ" aria-label="Decrease altitude">↓ Lower</button></div>`;document.body.appendChild(controls);
  const button=document.createElement('button');button.id='open-hangar';button.className='primary';button.textContent='Choose a vehicle';el('controls').prepend(button);
  button.onclick=()=>{if(!ready){status('Wait for the city map to load, then enter the helicopter.');return;}el('hangar').hidden=false;el('start-flight').focus();};el('close-hangar').onclick=()=>{el('hangar').hidden=true;button.focus();};el('vehicle').onchange=()=>{const auto=el('vehicle').value==='auto';el('start-flight').textContent=auto?'Enter auto':'Enter helicopter';el('departure-pad').hidden=auto;document.querySelector('label[for="departure-pad"]').hidden=auto;el('hangar').querySelector('p').textContent=auto?'Drive a green-and-yellow auto freely around the central district.':'Fly a utility helicopter with banking, momentum and a spring-follow chase camera.';el('hangar').querySelector('.note').textContent=auto?'Arrow keys drive and steer. Space brakes. Building contact and road/grass grip. No traffic simulation.':'Arcade flight, virtual landing pads, flat terrain. No obstacle collisions.';};el('start-flight').onclick=async()=>{if(el('vehicle').value!=='auto'){return start();}const button=el('start-flight');button.disabled=true;button.textContent='Preparing auto…';el('hangar-error').textContent='';try{const module=await import('./auto-mode.js');await module.startAuto(map);}catch(e){console.error(e);el('hangar-error').textContent='Auto could not load. Check your connection and retry.';}finally{button.disabled=false;button.textContent='Enter auto';}};el('exit-flight').onclick=exit;el('takeoff').onclick=takeoff;el('pause-flight').onclick=()=>setPaused(!paused);el('reset-flight').onclick=reset;el('camera-flight').onclick=()=>{cameraMode=({chase:'overhead',overhead:'shield',shield:'chase'})[cameraMode];el('camera-flight').textContent=({chase:'Overhead view',overhead:'CBD shield',shield:'Chase view'})[cameraMode];camera(1,true);map.triggerRepaint();};
  const tip=document.createElement('div');tip.id='flight-mouse-tip';tip.hidden=true;tip.textContent='Drag to steer · Wheel or Q/E to change altitude · Space to hover';document.body.append(tip);
 const normal=code=>({ShiftRight:'ShiftLeft',KeyW:'ArrowUp',KeyS:'ArrowDown',KeyA:'ArrowLeft',KeyD:'ArrowRight'}[code]||code);
 const allowed=new Set(['ShiftLeft','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space']);
  document.addEventListener('keydown',e=>{if(!active||e.target.matches('input,select,textarea'))return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)setPaused(!paused);return;}if((e.code==='KeyL'||(e.code==='Enter'&&!e.target.matches('button')))&&!e.repeat){e.preventDefault();takeoff();return;}const code=normal(e.code);if(allowed.has(code)){e.preventDefault();if(!paused){keys.add(code);if(code==='ArrowUp'&&phase==='parked')takeoff();map.getCanvas().focus({preventScroll:true});}}});
  document.addEventListener('keyup',e=>keys.delete(normal(e.code)));
  const canvas=el('map');canvas.addEventListener('pointerdown',e=>{if(!active||paused||e.pointerType==='touch'||e.button!==0||!e.target.matches('canvas'))return;e.preventDefault();mouse={id:e.pointerId,x:e.clientX,y:e.clientY,turn:0,forward:0};canvas.setPointerCapture(e.pointerId);map.getCanvas().style.cursor='grabbing';if(phase==='parked')takeoff();});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==mouse.id)return;const dx=e.clientX-mouse.x,dy=e.clientY-mouse.y;mouse.turn=clamp(Math.sign(dx)*Math.max(0,Math.abs(dx)-5)/130,-1,1);mouse.forward=clamp(-Math.sign(dy)*Math.max(0,Math.abs(dy)-5)/130,-1,1);});for(const name of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(name,e=>{if(e.pointerId===mouse.id){mouse.id=null;mouse.turn=mouse.forward=0;map.getCanvas().style.cursor='';}});canvas.addEventListener('wheel',e=>{if(!active||paused||!e.target.matches('canvas'))return;e.preventDefault();wheelLift=-Math.sign(e.deltaY);wheelUntil=performance.now()+250;},{passive:false});
  document.querySelectorAll('[data-flight-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(!active||paused)return;b.setPointerCapture(e.pointerId);keys.add(b.dataset.flightKey);if(b.dataset.flightKey==='ArrowUp'&&phase==='parked')takeoff();b.classList.add('held');});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>{keys.delete(b.dataset.flightKey);b.classList.remove('held');});});
  window.addEventListener('blur',()=>{if(active)setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&active)setPaused(true);});
  // Read-only diagnostics for regression checks; no simulation-state mutation hook.
  document.addEventListener('keydown',e=>{if(active&&!e.target.matches('input,select,textarea')&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyQ','KeyE','ShiftLeft'].includes(e.code))roaming=false;},true);
  window.setFlightRoam=value=>{if(!active)return false;roaming=!!value;if(roaming){setPaused(false);if(phase==='parked')takeoff();}return roaming;};
  window.startFlightTakeoff=()=>{if(!active)return;if(paused)setPaused(false);takeoff();updateHUD();};
  window.flightCameraControls={orbit(dx,dy){if(!active)return;window.setDomeOverview?.(false);cameraMode='chase';cameraOrbitYaw=(cameraOrbitYaw+dx)%360;cameraOrbitLift=clamp(cameraOrbitLift+dy,-12,95);camera(1,true);map.triggerRepaint();}};
  window.flightState=()=>({roaming,active,paused,phase,lng,lat,boost:dynamics?{...dynamics.boost}:null,altitude:alt-2,heading,speed,travel,cameraMode,cameraOrbitYaw,cameraOrbitLift,rotorAngle,rotorPower,pitch:dynamics?.pitch||0,roll:dynamics?.roll||0,yawRate:dynamics?.yawRate||0,velocity:dynamics?{x:dynamics.vx,y:dynamics.vy,z:dynamics.vz}:null,cameraPosition:cameraRig?{x:cameraRig.x,y:cameraRig.y,z:cameraRig.z}:null,tilt:tilt?.state(),gamepad:gamepad?.state(),mouse:{turn:mouse.turn,forward:mouse.forward,dragging:mouse.id!==null},keys:[...keys]});
 }
 init();
})();


