const held=new Set(),touches=new Map();let boostTimer=0,lastSwipe=null,hoverTimer=0,lastTap=null,frame=0,lastFrame=0;
const driveInput={throttle:0,reverse:0,steer:0};
const analog=value=>Math.sign(value)*Math.min(1,Math.max(0,(Math.min(1,Math.abs(value))-.18)/.82));
function clearAnalog(){driveInput.throttle=driveInput.reverse=driveInput.steer=0;}
window.mobileDriveInput=()=>({...driveInput});
const ride=()=>window.autoState?.().active?'auto':window.flightState?.().active?'flight':'';
function key(code,on){if(on===held.has(code))return;on?held.add(code):held.delete(code);document.querySelector('#map canvas')?.dispatchEvent(new KeyboardEvent(on?'keydown':'keyup',{code,key:code,bubbles:true}));}
const sticks={};for(const side of ['left','right']){const el=document.createElement('div');el.className='floating-ride-stick';el.dataset.side=side;el.hidden=true;el.innerHTML='<span></span>';el.setAttribute('aria-hidden','true');document.body.append(el);sticks[side]=el;}
function clearDrive(){clearAnalog();for(const code of ['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'])key(code,false);}
function release(){clearAnalog();const old=[...touches.values()];touches.clear();for(const t of old)try{t.target.releasePointerCapture(t.id);}catch{};for(const el of Object.values(sticks))el.hidden=true;for(const code of [...held])key(code,false);clearTimeout(hoverTimer);clearTimeout(boostTimer);lastSwipe=null;cancelAnimationFrame(frame);frame=lastFrame=0;lastTap=null;}
function hover(){if(!ride())return;key('Space',true);clearTimeout(hoverTimer);hoverTimer=setTimeout(()=>key('Space',false),900);}
function tick(){frame=lastFrame=0;}
function down(e){if(e.pointerType!=='touch'||!ride()||document.body.classList.contains('mobile-tools-open')||!e.target.matches('#map canvas'))return;e.preventDefault();e.stopImmediatePropagation();const side=e.clientX<innerWidth/2?'left':'right';if([...touches.values()].some(t=>t.side===side))return;const t={id:e.pointerId,side,target:e.target,cx:e.clientX,cy:e.clientY,x:0,y:0,time:e.timeStamp,moved:0,multi:touches.size>0};if(t.multi)for(const p of touches.values())p.multi=true;touches.set(t.id,t);t.target.setPointerCapture(t.id);const el=sticks[side];el.style.left=t.cx+'px';el.style.top=t.cy+'px';el.firstChild.style.transform='translate(0,0)';el.hidden=side!=='left';if(!frame)frame=requestAnimationFrame(tick);}
function move(e){const t=touches.get(e.pointerId);if(!t)return;e.preventDefault();e.stopImmediatePropagation();const dx=e.clientX-t.cx,dy=e.clientY-t.cy;t.moved=Math.max(t.moved,Math.hypot(dx,dy));const length=Math.max(42,Math.hypot(dx,dy));t.x=dx/length;t.y=dy/length;sticks[t.side].firstChild.style.transform=`translate(${t.x*27}px,${t.y*27}px)`;if(t.side==='left'){if(ride()==='auto'){const forward=analog(-t.y);driveInput.throttle=Math.max(0,forward);driveInput.reverse=Math.max(0,-forward);driveInput.steer=analog(t.x);}else{clearAnalog();key('ArrowLeft',t.x<-.25);key('ArrowRight',t.x>.25);key('ArrowUp',t.y<-.25);key('ArrowDown',t.y>.25);}}}
function up(e){const t=touches.get(e.pointerId);if(!t)return;e.preventDefault();e.stopImmediatePropagation();touches.delete(t.id);sticks[t.side].hidden=true;if(t.side==='left')clearDrive();try{t.target.releasePointerCapture(t.id);}catch{};const now=e.timeStamp;if(e.type==='pointerup'&&!t.multi&&t.side==='left'&&t.y<-.65&&t.moved>45&&now-t.time<450){if(lastSwipe&&now-lastSwipe<650){key('ShiftLeft',true);clearTimeout(boostTimer);boostTimer=setTimeout(()=>key('ShiftLeft',false),2000);lastSwipe=null;}else lastSwipe=now;}else if(e.type!=='pointerup'){lastSwipe=null;}if(e.type==='pointerup'&&!t.multi&&t.moved<14&&now-t.time<300){if(lastTap&&now-lastTap.time<450&&Math.hypot(t.cx-lastTap.x,t.cy-lastTap.y)<36){hover();lastTap=null;}else lastTap={time:now,x:t.cx,y:t.cy};}else lastTap=null;}
document.addEventListener('pointerdown',down,{capture:true,passive:false});document.addEventListener('pointermove',move,{capture:true,passive:false});for(const type of ['pointerup','pointercancel','lostpointercapture'])document.addEventListener(type,up,{capture:true,passive:false});window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden)release();});
const demo=document.createElement('aside');demo.id='mobile-drive-demo';demo.hidden=true;demo.innerHTML='<strong>Drag left to drive</strong><p>Use your left thumb to steer and move.<br>Double-tap to stop / hover.<br>Swipe up twice quickly for a 2-second boost.</p><button type="button">Got it</button>';document.body.append(demo);let demoTimer;demo.querySelector('button').onclick=()=>{demo.hidden=true;clearTimeout(demoTimer);try{localStorage.setItem('opencity-touch-demo-3','seen');}catch{}};
let demoShown=false;
function showDemo(){if(demoShown||!matchMedia('(pointer:coarse)').matches)return;demoShown=true;try{if(localStorage.getItem('opencity-touch-demo-3'))return;}catch{}demo.hidden=false;demoTimer=setTimeout(()=>demo.querySelector('button').click(),8000);}
window.mobileDriveState=()=>({pointers:[...touches.values()].map(t=>({id:t.id,side:t.side,x:t.x,y:t.y})),keys:[...held],analog:{...driveInput},lastTap});
let lastRide='';setInterval(()=>{const ride=window.autoState?.().active?'auto':window.flightState?.().active?'flight':'';if(lastRide!==ride){release();lastRide=ride;if(ride)showDemo();else demo.hidden=true;}const holder=ride&&document.querySelector('#'+ride+'-hud .controller-options-body');if(holder&&!holder.querySelector('.mobile-vehicle-actions')){const group=document.createElement('div');group.className='mobile-vehicle-actions';for(const id of (ride==='auto'?['pause-auto','auto-camera','exit-auto']:['takeoff','pause-flight','camera-flight','exit-flight'])){const b=document.createElement('button');b.type='button';b.dataset.control=id;b.onclick=()=>{if(id==='takeoff')window.startFlightTakeoff?.();else document.getElementById(id)?.click();document.getElementById('mobile-menu-close')?.click();};group.append(b);}holder.prepend(group);}document.querySelectorAll('.mobile-vehicle-actions button').forEach(b=>b.textContent=document.getElementById(b.dataset.control)?.textContent||'');},150);




