import {paintHex,selectedVehicleColor,wireVehicleColor} from './vehicle-colors.js';
// Shared-room transport. Link possession grants guest access; no account is required.
const make=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;};
const cleanName=value=>String(value||'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,24);
let name='';try{name=cleanName(localStorage.getItem('opencity-player-name')||sessionStorage.getItem('opencity-player-name'));if(name)localStorage.setItem('opencity-player-name',name);}catch{}
let room=new URL(location.href).searchParams.get('room')||'',id=null,players=[],socket=null,retryTimer=null,attempt=0,wanted=false,suspended=false,status='Solo',endpoint='',generation=0,lastMessage=0;
const validRoom=value=>/^[a-f0-9]{32}$/.test(value);
const panel=make('details','multiplayer-panel');panel.id='multiplayer-panel';
const summary=make('summary'),badge=make('span','multiplayer-badge'),statusText=make('span','multiplayer-status','Solo');summary.append(badge,statusText);panel.append(summary);
const content=make('div','multiplayer-content'),hint=make('p','multiplayer-hint','Meet friends in the same CBD. Up to 8 players.');
const actions=make('div','multiplayer-actions'),host=make('button','','Create room'),copy=make('button','','Copy invite'),reconnect=make('button','','Reconnect'),leave=make('button','','Leave'),rename=make('button','','Change name');
for(const b of [host,copy,reconnect,leave,rename]){b.type='button';actions.append(b);}
const roster=make('ul','multiplayer-roster');roster.setAttribute('aria-label','Players in this room');
const notice=make('p','multiplayer-notice');notice.setAttribute('role','status');
const invite=make('input','multiplayer-invite');invite.readOnly=true;invite.setAttribute('aria-label','Invite link');invite.hidden=true;
const joinForm=make('form','multiplayer-join'),joinCode=make('input'),joinButton=make('button','','Join room');joinCode.placeholder='Paste invite link or room code';joinCode.setAttribute('aria-label','Invite link or room code');joinCode.required=true;joinButton.type='submit';joinForm.append(joinCode,joinButton);
content.append(hint,actions,joinForm,invite,roster,notice);panel.append(content);document.body.append(panel);
const roomToggle=make('button','desktop-room-toggle','Room');roomToggle.type='button';roomToggle.setAttribute('aria-controls','multiplayer-panel');roomToggle.setAttribute('aria-expanded','false');roomToggle.onclick=()=>{panel.open=!panel.open;roomToggle.setAttribute('aria-expanded',String(panel.open));};document.body.append(roomToggle);
const directory=make('section','room-directory'),directoryHeading=make('div','room-directory-heading'),directoryTitle=make('h3','','Public rooms'),directoryRefresh=make('button','','Refresh'),directoryStatus=make('p','room-directory-status'),directoryList=make('ul','room-directory-list');directoryRefresh.type='button';directoryRefresh.setAttribute('aria-label','Refresh public rooms');directoryStatus.setAttribute('role','status');directoryHeading.append(directoryTitle,directoryRefresh);directory.append(directoryHeading,directoryStatus,directoryList);content.append(directory);let directoryRequest=0,directoryAbort=null;
async function loadPublicRooms(){const request=++directoryRequest;directoryAbort?.abort();const controller=new AbortController();directoryAbort=controller;const signal=controller.signal,timer=setTimeout(()=>controller.abort(),10000);directoryRefresh.disabled=true;directoryStatus.textContent='Loading public rooms…';directoryList.replaceChildren();try{let voiceEndpoint=endpoint;if(!voiceEndpoint){const configResponse=await fetch('./multiplayer-config.json',{cache:'no-store',signal});if(!configResponse.ok)throw Error('Room configuration unavailable.');voiceEndpoint=(await configResponse.json()).url;}const url=new URL(voiceEndpoint);if(!['ws:','wss:'].includes(url.protocol))throw Error('Invalid room server.');url.protocol=url.protocol==='wss:'?'https:':'http:';url.pathname='/rooms';url.search='';url.hash='';const response=await fetch(url.href,{cache:'no-store',credentials:'omit',signal});if(!response.ok)throw Error('Public rooms are temporarily unavailable.');const data=await response.json();if(!Array.isArray(data.rooms))throw Error('Invalid room directory response.');if(request!==directoryRequest||!panel.open)return;const rooms=data.rooms.map(item=>({...item,id:item.room,count:item.playerCount})).filter(item=>validRoom(item.id)&&Number.isInteger(item.count)&&Number.isInteger(item.capacity)&&item.count>0&&item.capacity>0&&item.count<=item.capacity).slice(0,100);for(const item of rooms){const row=make('li','room-directory-item'),info=make('div'),title=make('strong','',String(item.label||('Public room '+item.id.slice(0,6))).slice(0,80)),count=make('small','',`${item.count} / ${item.capacity} players`),button=make('button','',item.id===room&&id?'Current':item.count>=item.capacity?'Full':'Join');button.type='button';button.disabled=(item.id===room&&!!id)||item.count>=item.capacity;button.setAttribute('aria-label',`${button.textContent} public room ${item.id.slice(0,6)}`);button.onclick=()=>{room=item.id;roomAction='join';attempt=0;panel.open=false;if(!name)promptName();else connect();};info.append(title,count);row.append(info,button);directoryList.append(row);}directoryStatus.textContent=rooms.length?'Only public rooms are listed.':'No public rooms are active. Choose Free room to start one.';}catch(error){if(request!==directoryRequest||!panel.open)return;directoryStatus.textContent=error.name==='AbortError'?'Room list timed out. Refresh to retry.':`${error.message} Refresh to retry.`;}finally{clearTimeout(timer);if(request===directoryRequest)directoryRefresh.disabled=false;}}
directoryRefresh.onclick=loadPublicRooms;
panel.addEventListener('toggle',()=>{roomToggle.setAttribute('aria-expanded',String(panel.open));if(panel.open)loadPublicRooms();else{directoryRequest++;directoryAbort?.abort();directoryRefresh.disabled=false;}});
const dialog=make('dialog','multiplayer-name-dialog'),form=make('form'),title=make('h2','','What should we call you?'),description=make('p','','Your name appears above your vehicle and in your meetup.'),label=make('label','','Player name'),input=make('input');input.maxLength=24;input.required=true;input.autocomplete='nickname';input.placeholder='Your name';label.append(input);
let entryMode='entry',roomAction='create',isPublic=false;
const entryActions=make('div','multiplayer-entry-actions'),createEntry=make('button','','Create room'),joinEntry=make('button','','Join room');createEntry.type='submit';createEntry.value='create';joinEntry.type='button';const openEntry=make('button','','Free room');openEntry.type='submit';openEntry.value='open';const hostMeetup=make('button','','Host a meetup'),browseMeetups=make('button','','Meetups');hostMeetup.type=browseMeetups.type='button';entryActions.append(createEntry,joinEntry,openEntry);
const symbols={create:'<path d="M12 5v14M5 12h14"/>',join:'<path d="M13 5h6v14h-6M3 12h11M10 8l4 4-4 4"/>',open:'<circle cx="12" cy="12" r="8"/><path d="m15 9-2 4-4 2 2-4z"/>'};
for(const [button,key,heading,detail] of [[createEntry,'create','Create room','Your space. Invite your people.'],[joinEntry,'join','Join room','Have an invite? Meet them inside.'],[openEntry,'open','Free room','Drop into a public room and explore.']]){button.classList.add('room-choice');button.setAttribute('aria-label',heading);button.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">'+symbols[key]+'</svg><span><strong>'+heading+'</strong><small>'+detail+'</small></span><span class="room-choice-arrow" aria-hidden="true">&#8599;</span>';}
const roomLabel=make('label','multiplayer-entry-room','Room invite or code'),entryCode=make('input');entryCode.placeholder='Paste invite link or room code';entryCode.autocomplete='off';roomLabel.append(entryCode);roomLabel.hidden=true;
const submit=make('button','','Join and start');submit.type='submit';submit.value='join';submit.hidden=true;const entryNotice=make('p','multiplayer-entry-notice');entryNotice.setAttribute('role','status');
const remembered=make('div','multiplayer-remembered'),rememberedName=make('span'),editRemembered=make('button','','Edit name');editRemembered.type='button';remembered.append(rememberedName,editRemembered);const brand=make('div','entry-brand','OpenCity'),foot=make('p','entry-foot','Bengaluru CBD · Up to 8 players per room');form.append(brand,title,description,remembered,label,entryActions,roomLabel,submit,entryNotice,foot);dialog.append(form);document.body.append(dialog);
const meetupView=make('section','multiplayer-meetup-view');meetupView.hidden=true;const meetupBack=make('button','','← Room choices'),meetupTitle=make('h2'),meetupStatus=make('p','multiplayer-entry-notice'),meetupBody=make('div');meetupBack.type='button';meetupStatus.setAttribute('role','status');meetupView.append(meetupBack,meetupTitle,meetupBody,meetupStatus);dialog.append(meetupView);let meetupAdapter=null;
meetupBack.onclick=()=>{meetupView.hidden=true;form.hidden=false;};
function rememberEntryName(){const value=cleanName(input.value);if(!value){label.hidden=false;input.focus();input.reportValidity();return false;}name=value;try{localStorage.setItem('opencity-player-name',name);sessionStorage.setItem('opencity-player-name',name);}catch{}rememberedName.textContent='Playing as '+name;render();dispatch();return true;}
function meetupScreen(titleText){if(!rememberEntryName())return false;form.hidden=true;meetupView.hidden=false;meetupTitle.textContent=titleText;meetupBody.replaceChildren();meetupStatus.textContent='';return true;}
function meetupField(parent,text,type,value=''){const field=make('label','',text),control=make('input');control.type=type;control.value=value;control.required=true;field.append(control);parent.append(field);return control;}
hostMeetup.onclick=()=>{if(!meetupScreen('Host a meetup'))return;const f=make('form','multiplayer-meetup-form');let draft={};try{draft=JSON.parse(localStorage.getItem('opencity-meetup-draft')||'{}');}catch{}const topic=meetupField(f,'Topic','text',draft.topic||'');topic.maxLength=120;const hostName=meetupField(f,'Host','text',name);hostName.readOnly=true;const schedule=meetupField(f,'Schedule (your local time)','datetime-local',draft.localSchedule||'');const attendance=meetupField(f,'Expected attendance','number',String(draft.expectedAttendance||4));attendance.min=1;attendance.max=8;const capacity=make('p','','Current rooms support up to 8 players.'),save=make('button','',meetupAdapter?'Publish meetup':'Save draft on this device');save.type='submit';f.append(capacity,save);meetupBody.append(f);meetupStatus.textContent=meetupAdapter?'Publishing is connected.':'Meetup publishing is not connected yet. You can save a draft on this device.';f.onsubmit=async e=>{e.preventDefault();const date=new Date(schedule.value);if(!Number.isFinite(date.getTime())||date.getTime()<=Date.now()){meetupStatus.textContent='Choose a future date and time.';return;}const data={topic:topic.value.trim(),host:name,scheduledAt:date.toISOString(),localSchedule:schedule.value,expectedAttendance:Number(attendance.value)};if(!data.topic)return;save.disabled=true;try{if(meetupAdapter){await meetupAdapter.create(data);meetupStatus.textContent='Meetup published.';}else{localStorage.setItem('opencity-meetup-draft',JSON.stringify(data));meetupStatus.textContent='Draft saved on this device. It is not published or visible to others.';}window.dispatchEvent(new CustomEvent('opencity-meetup-draft',{detail:data}));}catch(error){meetupStatus.textContent='Unable to save meetup: '+String(error.message||error);}finally{save.disabled=false;}};};
browseMeetups.onclick=async()=>{if(!meetupScreen('Meetups'))return;const open=make('button','','Join an open room now');open.type='button';open.onclick=()=>{room='';roomAction='open';connect();};meetupBody.append(open);if(!meetupAdapter){meetupStatus.textContent='Scheduled meetups are not connected yet. Open rooms are available now.';return;}meetupStatus.textContent='Loading meetups…';try{const events=await meetupAdapter.list();if(!Array.isArray(events))throw Error('Invalid meetup response');for(const event of events){const card=make('article','multiplayer-meetup-card'),heading=make('h3','',String(event.topic||'Meetup'));const date=new Date(event.scheduledAt);card.append(heading,make('p','',`Host: ${String(event.host||'Unknown')} · ${Number.isFinite(date.getTime())?date.toLocaleString():'Schedule unavailable'} · Expected: ${Number(event.expectedAttendance)||0}`));if(validRoom(event.room)){const join=make('button','','Join meetup');join.type='button';join.onclick=()=>{room=event.room;connect();};card.append(join);}meetupBody.append(card);}meetupStatus.textContent=events.length?'':'No scheduled meetups yet.';}catch(error){meetupStatus.textContent='Meetups unavailable: '+String(error.message||error);}};
// A persistent backend may register authenticated list/create methods when ready.
window.configureOpenCityMeetups=adapter=>{if(!adapter||typeof adapter.list!=='function'||typeof adapter.create!=='function')throw new TypeError('Meetups adapter requires list and create methods.');meetupAdapter=adapter;};
for(const e of [panel,dialog])for(const type of ['keydown','keyup','pointerdown','pointerup','wheel'])e.addEventListener(type,event=>event.stopPropagation());
const voicePending=new Map();let vehicleColor=selectedVehicleColor()||'green';
function dispatch(){if(!id){for(const pending of voicePending.values()){clearTimeout(pending.timer);pending.reject(Error('Room connection ended.'));}voicePending.clear();}window.dispatchEvent(new CustomEvent('multiplayer-players',{detail:{id,players,name}}));}
function render(){badge.textContent=name||'Player';statusText.textContent=status;copy.hidden=!room||!id;leave.hidden=!wanted;reconnect.hidden=!wanted||status==='Connected';host.hidden=wanted;joinForm.hidden=wanted;rename.hidden=false;roster.replaceChildren();for(const p of players){const item=make('li','',`${p.name}${p.id===id?' (you)':''}`);const vehicle=make('small','',p.pose?.vehicle||'spectator');item.append(vehicle);roster.append(item);}if(id)statusText.textContent=`${players.length}/8 online`;}
function setStatus(next,message){status=next;if(message!==undefined){notice.textContent=message;if(dialog.open){entryNotice.textContent=message;if(!meetupView.hidden)meetupStatus.textContent=message;}}render();}
function promptName(mode='entry'){entryMode=mode;input.value=name;label.hidden=!!name&&mode!=='rename';remembered.hidden=!name||mode==='rename';rememberedName.textContent='Playing as '+name;form.hidden=false;if(typeof meetupView!=='undefined')meetupView.hidden=true;title.textContent=mode==='rename'?'Your player name':'The city is yours.';description.textContent=mode==='rename'?'Your name appears above your vehicle.':'Pick your way into Bengaluru.';entryActions.hidden=mode==='rename';roomLabel.hidden=mode==='rename'||!room;entryCode.value=room;submit.hidden=mode!=='rename'&&!room;submit.textContent=mode==='rename'?'Save name':'Join and start';entryNotice.textContent='';if(!dialog.open)dialog.showModal();if(!name||mode==='rename')input.focus();else createEntry.focus();}
editRemembered.onclick=()=>{label.hidden=false;remembered.hidden=true;input.focus();};
function parseRoom(value){let code=value.trim();try{if(code.includes('://'))code=new URL(code).searchParams.get('room')||'';}catch{}return validRoom(code)?code:null;}
joinEntry.onclick=()=>{roomLabel.hidden=false;submit.hidden=false;entryCode.focus();};
form.addEventListener('submit',event=>{event.preventDefault();const value=cleanName(input.value);if(!value){input.setCustomValidity('Enter a name.');input.reportValidity();return;}if(entryMode!=='rename'){const action=event.submitter?.value||(!roomLabel.hidden?'join':'create');if(action==='join'){const code=parseRoom(entryCode.value);if(!code){roomLabel.hidden=false;submit.hidden=false;entryNotice.textContent='Paste a valid invite link or 32-character room code.';entryCode.focus();return;}room=code;roomAction='join';}else{room='';roomAction=action==='open'?'open':'create';}}name=value;try{sessionStorage.setItem('opencity-player-name',name);localStorage.setItem('opencity-player-name',name);}catch{}render();dispatch();if(entryMode==='rename'){dialog.close();panel.open=false;if(wanted||id)connect();}else{attempt=0;connect();}});input.addEventListener('input',()=>input.setCustomValidity(''));
dialog.addEventListener('cancel',event=>{if(entryMode!=='rename')event.preventDefault();});rename.onclick=()=>promptName('rename');
function shareURL(){const url=new URL(location.href);url.searchParams.set('room',room);url.hash='';return url.href;}
copy.onclick=async()=>{const value=shareURL();try{await navigator.clipboard.writeText(value);notice.textContent='Invite copied. Anyone with this link can join.';}catch{invite.value=value;invite.hidden=false;invite.select();notice.textContent='Copy this invite link.';}};
function stop(clearRoom=false){wanted=false;generation++;clearTimeout(retryTimer);retryTimer=null;const old=socket;socket=null;old?.close();id=null;players=[];if(clearRoom){room='';const url=new URL(location.href);url.searchParams.delete('room');history.replaceState(null,'',url);}invite.hidden=true;dispatch();setStatus('Solo','You left the room.');}
leave.onclick=()=>{stop(true);promptName();};host.onclick=()=>{room='';promptName();};reconnect.onclick=()=>{attempt=0;connect();};
joinForm.onsubmit=event=>{event.preventDefault();let code=joinCode.value.trim();try{if(code.includes('://'))code=new URL(code).searchParams.get('room')||'';}catch{}if(!validRoom(code)){notice.textContent='Use a valid invite link or 32-character room code.';return;}room=code;connect();};
async function connect(){if(!name){promptName();return;}wanted=true;clearTimeout(retryTimer);const token=++generation;const old=socket;socket=null;old?.close();id=null;players=[];dispatch();setStatus('Connecting','Connecting to your meetup…');try{if(!endpoint){const response=await fetch('./multiplayer-config.json',{cache:'no-store'});if(!response.ok)throw Error('Meetup configuration unavailable.');const config=await response.json();const target=new URL(config.url);if(target.protocol!=='wss:'&&!(location.hostname==='127.0.0.1'&&target.protocol==='ws:'))throw Error('Meetup server URL is invalid.');endpoint=target.href;}if(token!==generation||!wanted)return;const ws=new WebSocket(endpoint);socket=ws;
 const timeout=setTimeout(()=>{if(socket===ws&&!id)ws.close();},12000);
 ws.onopen=()=>{if(token!==generation)return;ws.send(JSON.stringify({type:room?'join':roomAction,name,protocol:1,world:'cbd-1',...(room?{room}:{} )}));};
 ws.onmessage=event=>{if(token!==generation)return;let message;try{message=JSON.parse(event.data);}catch{return;}lastMessage=Date.now();if(message.type==='error'&&['emote_rate_limited','invalid_emote'].includes(message.code)){notice.textContent=message.code==='emote_rate_limited'?'Wait a moment before saying hi again.':'Greeting unavailable.';return;}if(message.type==='voice-token'||message.type==='voice-error'){const pending=voicePending.get(message.requestId);if(pending){clearTimeout(pending.timer);voicePending.delete(message.requestId);if(message.type==='voice-error')pending.reject(Error(message.message||'Voice unavailable.'));else pending.resolve({url:message.url,token:message.token});}return;}if(message.type==='emote'){window.dispatchEvent(new CustomEvent('multiplayer-emote',{detail:{id:message.id,emote:message.emote}}));return;}if(message.type==='welcome'){if(!validRoom(message.room)||typeof message.id!=='string')return;clearTimeout(timeout);room=message.room;id=message.id;attempt=0;const url=new URL(location.href);url.searchParams.set('room',room);history.replaceState(null,'',url);setPlayers(message.players);isPublic=message.public===true;setStatus('Connected',isPublic?'Public room. Choose your ride and meet other players.':'Share an invite, then choose your ride.');dialog.close();panel.open=false;window.dispatchEvent(new CustomEvent('multiplayer-ready',{detail:{room,id,public:isPublic}}));}else if(message.type==='snapshot'&&id){setPlayers(message.players);}else if(message.type==='error'){clearTimeout(timeout);wanted=false;const errors={room_not_found:'This room has expired. Create a room or use another invite.',room_full:'This room is full. Try another room or create your own.',server_full:'All rooms are busy. Please retry shortly.',invalid_name:'Enter a valid player name.',version_mismatch:'Update OpenCity to join this room.'};const text=errors[message.code]||String(message.message||message.code||'Unable to join this meetup.');if(!dialog.open)promptName();entryNotice.textContent=notice.textContent=text;if(!meetupView.hidden)meetupStatus.textContent=text;ws.close();}else if(message.type==='ping'){ws.send(JSON.stringify({type:'pong'}));}};
 ws.onclose=()=>{clearTimeout(timeout);if(token!==generation)return;socket=null;id=null;players=[];dispatch();if(wanted){setStatus('Reconnecting','Connection lost. Your vehicle stays under your control.');schedule();}else setStatus('Offline',notice.textContent);};ws.onerror=()=>{};
 }catch(error){if(token!==generation)return;setStatus('Offline',error.message);schedule();}}
function schedule(){if(!wanted||suspended)return;const delay=Math.min(30000,1000*2**Math.min(attempt++,5));retryTimer=setTimeout(connect,delay);}
function setPlayers(value){if(!Array.isArray(value))return;players=value.slice(0,8).filter(p=>p&&typeof p.id==='string'&&typeof p.name==='string').map(p=>({...p,name:cleanName(p.name)}));render();dispatch();}
export function localPose(){const auto=window.autoState?.(),flight=window.flightState?.();if(auto?.active&&Array.isArray(auto.position))return{vehicle:auto.vehicleType||'auto',lng:auto.position[0],lat:auto.position[1],altitude:auto.groundHeight||0,heading:((auto.heading%360)+360)%360,pitch:auto.physics?.pitch||0,roll:auto.physics?.roll||0,speed:auto.speed};if(flight?.active)return{vehicle:'helicopter',lng:flight.lng,lat:flight.lat,altitude:flight.altitude,heading:((flight.heading%360)+360)%360,pitch:flight.pitch,roll:flight.roll,speed:flight.speed};return{vehicle:'spectator',lng:77.5945,lat:12.9755,altitude:0,heading:0,pitch:0,roll:0,speed:0};}
setInterval(()=>{if(socket?.readyState===WebSocket.OPEN&&id&&socket.bufferedAmount<16384){const pose={...localPose(),color:wireVehicleColor(vehicleColor)};if(Object.entries(pose).every(([k,v])=>k==='vehicle'||k==='color'||Number.isFinite(v)))socket.send(JSON.stringify({type:'pose',pose}));}},100);
window.addEventListener('online',()=>{if(wanted&&!id){attempt=0;connect();}});
window.addEventListener('pagehide',()=>{suspended=true;clearTimeout(retryTimer);socket?.close();});
window.addEventListener('pageshow',()=>{if(suspended){suspended=false;if(wanted){attempt=0;connect();}}});
window.requestVoiceToken=()=>new Promise((resolve,reject)=>{if(!id||socket?.readyState!==WebSocket.OPEN){reject(Error('Join a room first.'));return;}const requestId=crypto.randomUUID();const timer=setTimeout(()=>{voicePending.delete(requestId);reject(Error('Voice server did not respond.'));},12000);voicePending.set(requestId,{resolve,reject,timer});socket.send(JSON.stringify({type:'voice-token',requestId}));});
window.addEventListener('vehicle-color-change',e=>{if(paintHex(e.detail?.color))vehicleColor=e.detail.color;});
window.sendQuickEmote=emote=>{if(emote!=='hi'||!id||socket?.readyState!==WebSocket.OPEN)return false;socket.send(JSON.stringify({type:'emote',emote}));return true;};
window.multiplayerState=()=>({name,room,id,status,public:isPublic,connected:!!id,players:players.map(p=>({...p})),lastMessage,pose:localPose()});
if(room&&!validRoom(room)){room='';notice.textContent='Invalid invite. Start a new meetup.';}
function enterWhenReady(){render();dispatch();if(room&&name)connect();else promptName();}
if(window.cityBootReady)enterWhenReady();else window.addEventListener('city-ready',enterWhenReady,{once:true});

let riding=document.body.classList.contains('flight-active');
new MutationObserver(()=>{const next=document.body.classList.contains('flight-active');if(next&&!riding)panel.open=false;riding=next;}).observe(document.body,{attributes:true,attributeFilter:['class']});
