import {loadVehicleAsset} from './blender-vehicle.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {loadDrivingData} from './driving-data.js';
import {buildRoadGraph,toLocal,roadPosition,advanceRoad,reverseRoad,bearing,toLngLat} from './auto-roads.js';
export function cbdRoadGraph(data){return buildRoadGraph({...data,features:data.features.filter(f=>f.geometry.type==='LineString'&&f.geometry.coordinates.every(p=>{const q=toLocal(p);return(q[0]/900)**2+(q[1]/930)**2<1;}))});}
export function nearestRoute(graph,p){let best,dist=Infinity;graph.edges.forEach((e,i)=>{if(!graph.connected.has(e.a))return;const a=graph.nodes[e.a].p,b=graph.nodes[e.b].p,dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(e.length*e.length)));const d=Math.hypot(p[0]-a[0]-dx*t,p[1]-a[1]-dy*t);if(d<dist){dist=d;best={edge:i,from:e.a,to:e.b,progress:e.length*t,ended:false};}});return {path:best,distance:dist};}
export function stepRoute(graph,path,metres){advanceRoad(graph,path,metres,'explore');if(path.ended)reverseRoad(graph,path);return {point:roadPosition(graph,path),heading:bearing(graph.nodes[path.from].p,graph.nodes[path.to].p)};}
export async function installTraffic(map){
 const [T,data]=await Promise.all([import('https://unpkg.com/three@0.169.0/build/three.module.js'),loadDrivingData()]);const graph=cbdRoadGraph(data),mobile=matchMedia('(pointer:coarse), (max-width:760px)').matches,count=mobile?8:20;
 const edges=graph.edges.map((e,i)=>({e,i})).filter(({e})=>graph.connected.has(e.a)&&e.length>30);if(!edges.length)return;
 const cars=Array.from({length:count},(_,i)=>{const {e,i:edge}=edges[Math.floor(i*edges.length/count)];return{path:{edge,from:e.a,to:e.b,progress:e.length*.35,ended:false},speed:4+i%4};});
 // Four shared material batches use the authored Cybercab, not box placeholders.
 const asset=(await loadVehicleAsset('cybercab')).clone(true);asset.rotation.x=Math.PI/2;asset.updateMatrixWorld(true);const batches=new Map();
 asset.traverse(o=>{if(!o.isMesh)return;const key=o.material.name;if(!batches.has(key))batches.set(key,{material:o.material.clone(),geometries:[]});batches.get(key).geometries.push(o.geometry.clone().applyMatrix4(o.matrixWorld).toNonIndexed());});
 const meshes=[...batches.values()].map(b=>{const geometry=mergeGeometries(b.geometries);b.geometries.forEach(g=>g.dispose());const m=new T.InstancedMesh(geometry,b.material,count);m.frustumCulled=false;return m;});
 const trianglesPerVehicle=meshes.reduce((n,m)=>n+(m.geometry.index?.count||m.geometry.attributes.position.count)/3,0);
 const scene=new T.Scene(),camera=new T.Camera();scene.add(...meshes,new T.HemisphereLight(0xffffff,0x657866,2));const origin=maplibregl.MercatorCoordinate.fromLngLat([77.5945,12.9755]),scale=origin.meterInMercatorCoordinateUnits(),transform=new T.Matrix4().makeTranslation(origin.x,origin.y,0).scale(new T.Vector3(scale,-scale,scale)),dummy=new T.Object3D();let renderer,last=0,visible=0,submitMs=0,timer;
 map.addLayer({id:'npc-traffic',type:'custom',renderingMode:'3d',onAdd(m,gl){renderer=new T.WebGLRenderer({canvas:m.getCanvas(),context:gl});renderer.autoClear=false;timer=setInterval(()=>{if(!document.hidden)map.triggerRepaint();},mobile?50:33);},render(gl,args){if(document.hidden)return;const now=performance.now(),dt=last?Math.min((now-last)/1000,.1):0;last=now;const centre=toLocal(map.getCenter().toArray());visible=0;for(const car of cars){const state=stepRoute(graph,car.path,car.speed*dt);if(Math.hypot(state.point[0]-centre[0],state.point[1]-centre[1])>(mobile?350:650))continue;const a=state.heading*Math.PI/180;dummy.position.set(state.point[0]-Math.cos(a)*1.3,state.point[1]+Math.sin(a)*1.3,(window.vidhanaStreetPatch?.heightAt(...toLngLat(state.point))??0)+.03);dummy.rotation.z=-a;dummy.updateMatrix();for(const mesh of meshes)mesh.setMatrixAt(visible,dummy.matrix);visible++;}for(const mesh of meshes){mesh.count=visible;mesh.instanceMatrix.needsUpdate=true;}camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);renderer.resetState();const start=performance.now();renderer.render(scene,camera);submitMs=performance.now()-start;window.recordCityRender?.('NPC traffic',renderer,submitMs);renderer.resetState();},onRemove(){clearInterval(timer);for(const mesh of meshes){mesh.geometry.dispose();mesh.material.dispose();}renderer.dispose();}});
 window.npcTrafficState=()=>({vehicles:count,visible,drawCalls:visible?meshes.length:0,trianglesPerVehicle,submitMs,mobile,mode:'Local ambient traffic'});
}
