import {loadVehicleAsset} from './blender-vehicle.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {loadDrivingData} from './driving-data.js';
import {installVehicleEnvironment} from './vehicle-environment.js';
import {advanceTrafficRoute,routeState,tickTraffic,mappedControls,vehicleContact,retainTrafficLoops,applyTrafficDirections,trafficSpawnSafe} from './traffic-simulation.js';
import {buildRoadGraph,toLocal,toLngLat} from './auto-roads.js';
export function cbdRoadGraph(data){return applyTrafficDirections(buildRoadGraph({...data,features:data.features.filter(f=>f.geometry.type==='LineString'&&f.geometry.coordinates.every(p=>{const q=toLocal(p);return(q[0]/900)**2+(q[1]/930)**2<1;}))}),data);}
export function nearestRoute(graph,p){let best,dist=Infinity;graph.edges.forEach((e,i)=>{if(!graph.connected.has(e.a))return;const a=graph.nodes[e.a].p,b=graph.nodes[e.b].p,dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(e.length*e.length)));const d=Math.hypot(p[0]-a[0]-dx*t,p[1]-a[1]-dy*t);if(d<dist){dist=d;const from=e.allowedFrom??e.a;best={edge:i,from,to:from===e.a?e.b:e.a,progress:e.length*(from===e.a?t:1-t),ended:false};}});return {path:best,distance:dist};}
export function stepRoute(graph,path,metres){return advanceTrafficRoute(graph,path,metres);}
export async function installTraffic(map){
 const [T,data,furniture]=await Promise.all([import('https://unpkg.com/three@0.169.0/build/three.module.js'),loadDrivingData(),fetch('./assets/streets/furniture.json').then(r=>{if(!r.ok)throw Error('Traffic controls unavailable');return r.json();})]);const verified={...data,features:data.features.filter(f=>f.properties?.osm)},graph=retainTrafficLoops(applyTrafficDirections(cbdRoadGraph(verified),verified)),controls=mappedControls(furniture.items),mobile=matchMedia('(pointer:coarse), (max-width:760px)').matches,limit=mobile?8:20;
 const edges=graph.edges.map((e,i)=>({e,i})).filter(({e,i})=>graph.connected.has(e.a)&&graph.nodes[e.a].edges.includes(i)&&e.length>30);if(!edges.length)return;
 const cars=[];for(let i=0;i<edges.length*8&&cars.length<limit;i++){const {e,i:edge}=edges[(i*37)%edges.length],from=graph.trafficDirections.has(edge+':'+e.a)?e.a:e.b,to=from===e.a?e.b:e.a,path={edge,from,to,progress:e.length*(.1+(i%8)*.1),ended:false},p=routeState(graph,path),car={id:i,path,x:p.point[0],y:p.point[1],heading:p.heading,speed:0,cruise:4+i%4};if(trafficSpawnSafe(graph,car)&&!cars.some(other=>vehicleContact(car,other,5)))cars.push(car);}const count=cars.length;
 // Shared material batches use the supplied Cybercab LOD.
 const asset=(await loadVehicleAsset('cybercab',true)).clone(true);asset.rotation.x=Math.PI/2;asset.updateMatrixWorld(true);const batches=new Map();
 asset.traverse(o=>{if(!o.isMesh)return;const key=o.material.name;if(!batches.has(key))batches.set(key,{material:o.material.clone(),geometries:[]});batches.get(key).geometries.push(o.geometry.clone().applyMatrix4(o.matrixWorld).toNonIndexed());});
 const meshes=[...batches.values()].map(b=>{const geometry=mergeGeometries(b.geometries);b.geometries.forEach(g=>g.dispose());const m=new T.InstancedMesh(geometry,b.material,count);m.frustumCulled=false;return m;});
 const trianglesPerVehicle=meshes.reduce((n,m)=>n+(m.geometry.index?.count||m.geometry.attributes.position.count)/3,0);
 const scene=new T.Scene(),camera=new T.Camera();scene.add(...meshes,new T.HemisphereLight(0xffffff,0x657866,2));const origin=maplibregl.MercatorCoordinate.fromLngLat([77.5945,12.9755]),scale=origin.meterInMercatorCoordinateUnits(),transform=new T.Matrix4().makeTranslation(origin.x,origin.y,0).scale(new T.Vector3(scale,-scale,scale)),dummy=new T.Object3D();let renderer,last=0,visible=0,submitMs=0,simulationMs=0,timer,accumulator=0,disposeEnvironment;
 function playerBody(){const p=window.autoState?.();if(!p?.active||!p.position)return null;const [x,y]=toLocal(p.position);return {x,y,heading:p.heading,...vehicleSize(p.vehicleType)};}
 window.npcTrafficCollider=(x,y,heading,type)=>{const body={x,y,heading,...vehicleSize(type)};for(const car of cars){if(Math.hypot(car.x-x,car.y-y)>8)continue;const hit=vehicleContact(body,car,.12);if(hit)return hit;}return null;};
 map.addLayer({id:'npc-traffic',type:'custom',renderingMode:'3d',onAdd(m,gl){renderer=new T.WebGLRenderer({canvas:m.getCanvas(),context:gl});renderer.autoClear=false;disposeEnvironment=installVehicleEnvironment(T,renderer,scene);timer=setInterval(()=>{if(!document.hidden)map.triggerRepaint();},mobile?50:33);},render(gl,args){if(document.hidden){last=0;return;}const now=performance.now(),dt=last?Math.min((now-last)/1000,.1):0;last=now;accumulator+=dt;if(accumulator>=.05){const start=performance.now();tickTraffic(graph,cars,controls,Math.min(accumulator,.1),Date.now()/1000,playerBody());simulationMs=performance.now()-start;accumulator=0;}const centre=toLocal(map.getCenter().toArray());visible=0;for(const car of cars){if(Math.hypot(car.x-centre[0],car.y-centre[1])>(mobile?350:650))continue;dummy.position.set(car.x,car.y,(window.vidhanaStreetPatch?.heightAt(...toLngLat([car.x,car.y]))??0)+.03);dummy.rotation.z=-car.heading*Math.PI/180;dummy.updateMatrix();for(const mesh of meshes)mesh.setMatrixAt(visible,dummy.matrix);visible++;}for(const mesh of meshes){mesh.count=visible;mesh.instanceMatrix.needsUpdate=true;}camera.projectionMatrix.fromArray(args.defaultProjectionData.mainMatrix).multiply(transform);renderer.resetState();const start=performance.now();renderer.render(scene,camera);submitMs=performance.now()-start;window.recordCityRender?.('NPC traffic',renderer,submitMs);renderer.resetState();},onRemove(){clearInterval(timer);delete window.npcTrafficCollider;for(const mesh of meshes){mesh.geometry.dispose();mesh.material.dispose();}disposeEnvironment?.();renderer.dispose();}});
 window.npcTrafficState=()=>({vehicles:count,visible,drawCalls:visible?meshes.length:0,trianglesPerVehicle,submitMs,simulationMs,mobile,stopped:cars.filter(c=>c.speed<.1).length,mappedSignals:controls.filter(c=>c.kind==='signal').length,mappedStops:controls.filter(c=>c.kind==='stop').length,mode:'Local ambient traffic; simulated signals; verified OSM routes',cars:cars.map(c=>({x:c.x,y:c.y,heading:c.heading,speed:c.speed,stopped:c.stopped}))});
}
function vehicleSize(type){return ['cycle','yulu','bike','delivery'].includes(type)?{length:2,width:.7}:type==='auto'?{length:2.8,width:1.5}:type==='cybertruck'?{length:5.7,width:2.1}:{length:4.6,width:1.9};}
