const {chromium}=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4173');await page.waitForFunction(()=>ready,{timeout:60000});await page.locator('#open-hangar').click();await page.locator('#start-flight').click();await page.waitForFunction(()=>flightState().active,{timeout:60000});await page.waitForFunction(()=>map.areTilesLoaded(),{timeout:60000});
 assert.equal(await page.evaluate(()=>map.getMaxZoom()),22);assert((await page.evaluate(()=>map.getZoom()))>19,'Chase camera must not hit old explorer zoom cap');
 const initial=await page.evaluate(()=>flightState());await page.waitForFunction(a=>Math.abs(flightState().rotorAngle-a)>.3,initial.rotorAngle);const spun=await page.evaluate(()=>flightState());assert.equal(spun.heading,initial.heading);assert.equal(spun.roll,0);assert.equal(spun.pitch,0);
 await page.screenshot({path:'helicopter-close.png'});await page.locator('#takeoff').click();await page.waitForFunction(()=>flightState().phase==='flying',{timeout:20000});await page.keyboard.down('KeyW');await page.waitForFunction(()=>flightState().speed>12,{timeout:20000});await page.keyboard.down('KeyD');await page.waitForFunction(()=>flightState().roll>.15,{timeout:15000});await page.keyboard.up('KeyW');await page.keyboard.up('KeyD');await page.locator('#pause-flight').click();await page.screenshot({path:'helicopter-banking.png'});
 const state=await page.evaluate(()=>flightState());assert(state.pitch<0);assert(state.roll>0);assert(Object.values(state.cameraPosition).every(Number.isFinite));await page.locator('#exit-flight').click();assert.equal(await page.evaluate(()=>map.getMaxZoom()),19);
 await page.setViewportSize({width:390,height:844});await page.reload();await page.waitForFunction(()=>ready,{timeout:60000});await page.locator('#collapse').click();await page.locator('#open-hangar').click();await page.locator('#start-flight').click();await page.waitForFunction(()=>flightState().active,{timeout:60000});await page.locator('#takeoff').click();await page.waitForFunction(()=>flightState().phase==='flying',{timeout:20000});await page.locator('#pause-flight').click();await page.screenshot({path:'helicopter-new-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:['close chase zoom','rotor rotates while airframe stays level','banking and pitch visible','camera spring finite','zoom limit restored on exit','mobile framing'],bank:state.roll,pitch:state.pitch,errors}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
